### ISSUE TITLE
FlatLinearOperator._matvec changes self._charge_sector

### ISSUE THREAD

**Issue by aaeberharter** [tenpy/tenpy#108]
https://github.com/tenpy/tenpy/blob/967c4347d09b613795100ec8185c346979d5ac92/tenpy/linalg/sparse.py#L210-L225

If `self._charge_sector` is `None` when entering `_matvec` it will be set to whatever comes last in the iteration over all charge sectors. I recommend adding the line
```
    result[self._mask] = self.npc_to_flat(npc_vec)  # convert back into numpy ndarray.
self.charge_sector = None # <-- add this line
return result
```
in order to reset the charge sector back to its original.

**Comment by jhauschild** [comment]
Thank you very much for finding this and pointing it out!
