### ISSUE TITLE
About calculating the momentum for entanglement spectrum

### ISSUE THREAD

**Issue by Weicheng-Ye** [tenpy/tenpy#11]
Thank you for the wonderful package

I am using your package to do some dmrg calculation in 2D and I need to calculate the momentum for entanglement spectrum. However, I find the entanglement spectrum I get from the function (in the class ..networks.mps.MPS) compute_K() is different from any entanglement spectrum I get directly from the function entanglement_spectrum(), which calculates the entanglement spectrum for every site(bond). Also, the momentum I get, which I read from the angle of the entanglement spectrum, is not at all what I suppose (n*2Pi/Ly). I want to understand what entanglement_spectrum compute_K calculates and how to get the correct momentum I want. 
(The lattice I am using is Kagome lattice.)

**Comment by jhauschild** [comment]
see the [discusssion in the forum](https://tenpy.johannes-hauschild.de/viewtopic.php?f=7&t=8).
