### ISSUE TITLE
Generate output through logging

### ISSUE THREAD

**Issue by Lschoon** [tenpy/tenpy#110]
As discussed in #49, Python includes functionality for [logging](https://docs.python.org/3/howto/logging.html#logging-basic-tutorial). It would make sense for us to switch over from console output through print statements to using loggers. 

Given the table at the top of the linked page (copied below), we will need to decide when to use a logger, and when to keep our current output (for example, when raising warnings or errors, or printing DMRG statuses)

Task you want to perform | The best tool for the task
-- | --
Display console output for ordinary usage of a command line script or program | print()
Report events that occur during normal operation of a program (e.g. for status monitoring or fault investigation) | logging.info() (or logging.debug() for very detailed output for diagnostic purposes)
Issue a warning regarding a particular runtime event | warnings.warn() in library code if the issue is avoidable and the client application should be modified to eliminate the warninglogging.warning() if there is nothing the client application can do about the situation, but the event should still be noted
Report an error regarding a particular runtime event | Raise an exception
Report suppression of an error without raising an exception (e.g. error handler in a long-running server process) | logging.error(), logging.exception() or logging.critical() as appropriate for the specific error and application domain

**Comment by jhauschild** [comment]
This is implemented now.
