### ISSUE TITLE
GPU acceleration via CuPy

### ISSUE THREAD

**Issue by AlexSchuckert** [tenpy/tenpy#112]
Hi!
It could be worth including GPU support as e.g. SVD and matrix multiplication can be sped up drastically (especially if not many CPU cores are available). 

The package cupy has SVD, matrix mult, elementwise mult implemented in a numpy compatible format.

In [this work](https://arxiv.org/abs/1907.12044) speedups up to 77x have been found for TDVP.

**Comment by Jakob-Unfried** [comment]
We plan to support GPU acceleration via CUDA in the near future.

By the way, unlike most other matrix operations, SVD is really inefficient on GPUs and can be actually slower than on CPU.
