### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by stefan-divic** [tenpy/tenpy#115]
**Describe the bug**
Upon cloning the newest version of tenpy from the git repo
```
git clone https://github.com/tenpy/tenpy
cd tenpy
pip install -e ./
bash ./compile.sh
```
I began encountering a `Segmentation fault (core dumped)` error in various contexts, including when running the e_tdvp example. I'm on Ubuntu 18.04.5 LTS, x86-64. I am using python3.7.7 via miniconda3 (since python3.7.9 and above were found to cause `ImportError: libffi.so.7: cannot open shared object file: No such file or directory` errors.) I have tried running in a fresh tenpy installation.

**Minimal example or code extract**
```
(tenpy) stefan:~/tenpy/examples$ python e_tdvp.py 
```

**Error traceback**
```
Reading 'bc_MPS'='finite' for config SpinChain
Reading 'S'=0.5 for config SpinChain
Reading 'conserve'='Sz' for config SpinChain
Reading 'L'=10 for config SpinChain
Reading 'Jx'=1.0 for config SpinChain
Reading 'Jy'=1.0 for config SpinChain
Reading 'Jz'=1.0 for config SpinChain
Reading 'hx'=0.0 for config SpinChain
Reading 'hy'=0.0 for config SpinChain
Reading 'hz'=0.0 for config SpinChain
Reading 'muJ'=0.0 for config SpinChain
Reading 'start_time'=0 for config TDVP
Reading 'dt'=0.1 for config TDVP
Subconfig 'trunc_params'=Config(<4 options>, 'trunc_params') for config TDVP
Segmentation fault (core dumped)
```

Notably, I have no trouble using python3.7.9 on macOS v10.14.6 (x86_64), nor have I encountered the Segmentation fault error in any context when using either python3.7.7 or python3.7.9.

**Comment by jhauschild** [comment]
Sorry for the delay. I can't reproduce this on my machine, so I'd ask you to try a few more things:
- I just learned that  `python -X faulthandler e_tdvp.py` should help to get an explicit traceback at the core dump, see the [docs](https://docs.python.org/3/library/faulthandler.html).
Does it?
- does the error occur if you don't use the Cython parts? You can avoid the import of the compiled partst with 
```bash
export TENPY_OPTIMIZE=0
python e_tdvp.py
```
If the error still occurs, I'd claim that it's not an issue of TeNPy but your python installation or some third-party library (like numpy/scipy).
- make sure you use the python you're expecting to use: check the output of 
```python
import tenpy
print(tenpy)  # this will print the file path of the imported tenpy
tenpy.show_config()  
```
- try setting up a completely new, clean conda environment with 
```bash
# assuming that you're in the base folder of the TeNPy repo
conda env create -f environment.yml -n "new_tenpy_env"
conda activate new_tenpy_env
pip install -e ./
cd examples
python t_tdvp.py
```

**Comment by stefan-divic** [comment]
Your last suggestion did the trick. There must have been something wrong with one of my installations. Thank you!
