### ISSUE TITLE
About numpy warning in the new version

### ISSUE THREAD

**Issue by Weicheng-Ye** [tenpy/tenpy#12]
Thank you for the wonderful package

When I was using the new version of the program to do dmrg the following numpy warning appears at least a dozen times 

> C:\Software\Anaconda3\tenpy\linalg\np_conserved.py:2425: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_block = old_block[block_slice].reshape(new_block_shape)
.

I have checked the source code and I think it can at least be fixed by a simple for loop to avoid the annoying warning.

**Comment by jhauschild** [comment]
I haven't been using the pure python version of np_conserved in a while, so I didn't notice that warning.
The commit referenced above should remove the warning, at least at that position/linenumber.
Please tell me whether you still get this warning after updating to the latest git version; hopefully I can close this issue afterwards. I wish everything would be that easy to fix....

**Comment by Weicheng-Ye** [comment]
Thank you very much for the fix
However, when I use `python setup.py build_ext --inplace` to generate C code this time, I get the following mysterious traceback:

> Traceback (most recent call last):
  File "c:/My Programs/My DMRG/MainX.py", line 62, in <module>
    resultslist, psilist, Wlist, qlist = dmrg_run_2d(Lx, Ly, l, dmrg_params)
  File "c:/My Programs/My DMRG/MainX.py", line 47, in dmrg_run_2d
    results = dmrg.run(psi, M, dmrg_params)
  File "C:\Software\Anaconda3\lib\site-packages\tenpy\algorithms\dmrg.py", line 166, in run
    engine = Engine_class(psi, model, DMRG_params)
  File "C:\Software\Anaconda3\lib\site-packages\tenpy\algorithms\dmrg.py", line 287, in __init__
    self.init_env(model)
  File "C:\Software\Anaconda3\lib\site-packages\tenpy\algorithms\dmrg.py", line 346, in init_env
    self.environment_sweeps(start_env)
  File "C:\Software\Anaconda3\lib\site-packages\tenpy\algorithms\dmrg.py", line 535, in environment_sweeps
    self.sweep(optimize=False)
  File "C:\Software\Anaconda3\lib\site-packages\tenpy\algorithms\dmrg.py", line 584, in sweep
    i0, upd_env[0], upd_env[1], optimize=optimize, meas_E_trunc=meas_E_trunc)
  File "C:\Software\Anaconda3\lib\site-packages\tenpy\algorithms\dmrg.py", line 651, in update_bond
    self.set_B(i0, U, S, VH)
  File "C:\Software\Anaconda3\lib\site-packages\tenpy\algorithms\dmrg.py", line 960, in set_B
    B0 = U.split_legs(['(vL.p0)']).replace_label('p0', 'p')
  File "tenpy\linalg\np_conserved.pyx", line 1310, in tenpy.linalg.np_conserved.Array.split_legs
  File "tenpy\linalg\np_conserved.pyx", line 2425, in tenpy.linalg.np_conserved.Array._split_legs_worker
ValueError: Buffer dtype mismatch, expected 'intp_t' but got 'long'
C:\Software\Anaconda3\lib\site-packages\tenpy\tools\params.py:115: UserWarning: unused parameters for DMRG lanczos_params:
['E_tol', 'P_tol', 'min_gap']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
C:\Software\Anaconda3\lib\site-packages\tenpy\tools\params.py:115: UserWarning: unused parameters for DMRG:
['max_E_err', 'max_S_err', 'max_hours', 'mixer']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))

What is the meaning of this and how should I fix it?

**Comment by Weicheng-Ye** [comment]
Thank you again for the fix! It does work well on my linux clustter
I guess the problem is the environment of my windows laptop. I am closing the issue now, but I do hope you can explain what I should do to avoid the traceback on the Windows.

**Comment by Weicheng-Ye** [comment]
BTW, many people are reporting similar dtype mismatch problem on Windows, their fix is to import some more datatype, but I do not understand what to do to be specific

**Comment by jhauschild** [comment]
It seems to be a problem of converting between 32-bit and 64-bit integers.
Anaconda offers a 64-bit and 32-bit Installer for Windows. Which one did you choose?
Do you have a 64-bit windows?
What's the output of the following snippet?

    import tenpy
    import numpy as np
    print(tenpy.__full_version__)
    print(np.int, np.long, np.longlong, np.intp, np.int_)
    print(np.sort([3, 1]).dtype, np.array(range(3)).dtype)

**Comment by Weicheng-Ye** [comment]
This is the result:

> v0.3.0 git unknown using python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)] with numpy 1.15.2, scipy 1.1.0
<class 'int'> <class 'int'> <class 'numpy.int64'> <class 'numpy.int64'> <class 'numpy.int32'>
int32 int32

I have a 64-bit Windows and I believe I use 64-bit installer as well for Windows as you can see above. I agree that this is indeed a conversion problem.
