### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yeon-lee** [tenpy/tenpy#121]
**Describe the bug**
What algorithm are you calling / what are you trying to do?

MPS.correlation_length  has problem when charge_sector is [0], which is zero charge.

It automatically includes the largest one, therefore the correlation length of the first entry diverge.

For any sensible DMRG result, we can observe that psi.correlation_length(target=4, charge_sector=[0]) will cause a blow-up. When we are inspecting zero-charge sector, we should exclude this.

This should be very easy-fix and I would be happy to fix the code if this makes sense.

**Comment by jhauschild** [comment]
Indeed, that's a one-liner fix.
Thanks for pointing it out. It should have correctly worked for charge_sector=0, but if you explicitly added the brackets, it didn't.
