### ISSUE TITLE
BUG in exponentially decaying interaction

### ISSUE THREAD

**Issue by yeon-lee** [tenpy/tenpy#123]
**Describe the bug**
What algorithm are you calling / what are you trying to do?

I am using SpinModel and it seems that the exponential interaction does not seem to work. For example, if I set
    
   model_params = { 
        'Jx': 0,
        'Jy': 0,
        'Jz': 0.3,
        'Jxp': 0.,
        'Jyp': 0.,
        'Jzp': 0.,
        'hx': 0,
        'hy': 0,
        'hz': 0,
        'bc_MPS': 'infinite',
        'L': unitcell,
        'conserve': conserve,
        'verbose': verbose
    }

M = SpinModel(model_params)

M.add_exponentially_decaying_coupling(10, 0.1, 'Sx','Sx')

  M = SpinModel(model_params)
  M.add_exponentially_decaying_coupling(10, 0.1, 'Sx','Sx')
      
  dmrg_params = {
      #'mixer': True,  # setting this to True helps to escape local minima
      'mixer': True,
      'mixer_params': {
          'amplitude' : 1e-4,
          'disable_after' : 40,
          'verbose' : True,
      },
      'trunc_params': {
          'chi_max': 200,
          'svd_min': 1.e-10,
      },
      'max_sweeps': 100,
      'max_E_err': 1.e-10,
      'start_env': 20,
      #'chi_list': {0: 30, 30: 100, 60: 200, 80: 300},
      'chi_list': {0: 100},
      'verbose': verbose,
}

psi.canonical_form()

info = dmrg.run(psi, M, dmrg_params)

Then, it seems that the DMRG run behaves as if the exponentially decaying term does not exist. Is there any subtlety in the use of exponentially decaying coupling? When I look through the code, it does not seem to be the case.

**Comment by yeon-lee** [comment]
I believe it is worth to leave a remark -- dmrg.run() does not re-calculate H_MPO. Therefore, when we are adding further interactions, we should re-initialize the model. This solves the issue.

**Comment by jhauschild** [comment]
You're absolutely right, one needs to re-calculate H_MPO.
I've updated the code to raise a warning in case one of the `CouplingMPOModel.add_*` functions gets called, such that this won't be an issue any more in the future. Also, the code for re-initialization is now just calling `M.init_H_from_terms()`.
