### ISSUE TITLE
Use Lapack for non-Hermitian eigen-problem

### ISSUE THREAD

**Issue by aaeberharter** [tenpy/tenpy#126]
Inside the LanczosEvolution class scipy.linalg.expm is used to compute the matrix exponential of a non-Hermitian matrix:

https://github.com/tenpy/tenpy/blob/92bca609188be99293c7e171ffb2f7395aee7642/tenpy/linalg/lanczos.py#L368

scipy.expm is a thin wrapper around scipy.sparse.linalg.expm. Since the matrix is dense and of low dimension I suggest using numpy.linalg.eig instead, for example:

```
w, v = eig(T[:k + 1, :k + 1] * delta)
v_ = np.transpose(np.conj(v))
exp_dT_e0 = np.dot(v, np.dot(np.diag(np.exp(w)), np.dot(v_, e0)))
```
I noticed this problem because on some system configurations scipy.linalg.expm produced a segmentation fault.

**Comment by jhauschild** [comment]
Thanks for pointing this out; I didn't realize that `scipy.linalg.expm` was using sparse matrix diagonalization.
Lanczos assumes that `H` is hermitian, and certainly generates a hermitian tri-diagonal `T`, so we can even use `np.linalg.eigh`.
Also, I've simplified the multiplication a litte bit, avoiding the construction of `e0` alltogether.

**Comment by jhauschild** [comment]
By the way: great work, already providing a fix :+1:
