### ISSUE TITLE
conda install does not install the lates version

### ISSUE THREAD

**Issue by xaverm** [tenpy/tenpy#129]
I am trying to install the latest version using `conda install --channel=conda-forge physics-tenpy`.

`conda search tenpy` yields `physics-tenpy 0.8.4` as the latest version.

However, doing `conda install --channel=conda-forge physics-tenpy`, I'm getting
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done
## Package Plan ##
  environment location: /home/user/.anaconda3
  added / updated specs:
    - physics-tenpy
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    physics-tenpy-0.7.2        |   py38h82cb98a_2         879 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         879 KB
The following NEW packages will be INSTALLED:
  physics-tenpy      conda-forge/linux-64::physics-tenpy-0.7.2-py38h82cb98a_2
```
I.e. **only the 0.7.2 version is  offered**.

Forcing an 0.8.4 install with `conda install physics-tenpy=0.8.4` sends my machine into outer space, orbiting for ever, trying to solve environments without success.<br><br>

**How to get this**
To make sure I'm (at least) not fooled by some screwed up (ana)conda environment I did  
1. Take a linux machine (only have such at hand), hide away all previous anaconda / python installs
2. Install a completely fresh anaconda from `www.anaconda.com`
3. Add `conda-forge` channel and all dependencies from `https://raw.githubusercontent.com/tenpy/tenpy/main/environment.yml` to `.condarc`
4. Do `conda update -n base -c defaults conda` and `conda update --all`
5. Do `conda install --channel=conda-forge physics-tenpy`

This generates the described behavior.<br><br>

Going for more verbosity with `conda install -debug -c conda-forge physics-tenpy=0.8.4` returns a lot of additional blurb, which I'm happy to list in full, if that would be of any help to you. Most of it is of type  `DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 89902` and 
`DEBUG conda.resolve:generate_spec_constraints(926): generate_spec_constraints returning with clause count: 89901`<br><br>

**Any help would be most appreciated.**

**Comment by xaverm** [comment]
Pls. remove the 'bug' label. I cannot. I'm not claiming this is a 'bug'.

**Comment by xaverm** [comment]
Anyway, installation of 0.8.4 from source works for me. Still, it would helpful to know why conda install does not.

**Comment by jhauschild** [comment]
Hmm, I can reproduce the issue.
This is an issue about the [required dependencies specified here](https://github.com/conda-forge/physics-tenpy-feedstock/blob/master/recipe/meta.yaml#L18-L36).
Compared to 0.7.2, I bumped the required numpy/scipy versions to a little bit higher, and I tried to pin BLAS to using MKL following [these](https://conda-forge.org/docs/maintainer/knowledge_base.html#blas) instructions.
My hunch is that the latter is causing the issues. It also didn't "work" as I intended, because it still compiles with `HAVE_MKL=0`.
Let's regenerate the 0.8.4 package for now without pinning MKL

**Comment by jhauschild** [comment]
@xaverm can you please confirm that it works now?

**Comment by xaverm** [comment]
@jhauschild oops. Yes. Confirmed. (Was happy ever after with my install from source.) For me tenpy.show_config() shows: `compiled without HAVE_MKL`. Don't know if that's what it should be, but anyway, both of my `numpy` and `scipy` use `libraries = ['mkl_rt', 'pthread']` for all the `lapack...` and `blas...` stuff listed for them. So probably everything is fine now.
