### ISSUE TITLE
ncon implementation between different packages

### ISSUE THREAD

**Issue by NicolaDallaPozza** [tenpy/tenpy#131]
Comparing Tenpy's ncon implementation and the original formulation from [https://www.tensors.net/code](https://www.tensors.net/code) I have noticed a difference (check the following code)

`import numpy as np
from ncon import ncon as ncon_GlenEvenbly  # code from https://www.tensors.net/code
from tenpy.algorithms.network_contractor import ncon as ncon_tenpy

A = np.random.rand(8, 2, 4)
tns1 = ncon_tenpy([A, A], [[1, -1, -3], [1, -2, -4]], [1])
tns2 = ncon_tenpy([A, A], [[1, -1, -2], [1, -3, -4]], [1])
tns3 = ncon_GlenEvenbly([A, A], [[1, -1, -3], [1, -2, -4]], [1])
print(tns1.shape)  # gives (2, 4, 2, 4)
print(tns2.shape)  # gives (2, 4, 2, 4)
print(tns3.shape)  # gives (2, 2, 4, 4)
print(np.linalg.norm(tns1.to_ndarray()-tns2.to_ndarray()))  # gives 0.0`

I am new to Tenpy, but isn't the shape of tns1 supposed to be different from that of tns2 (and actually be equal to tns3)?

Another minor difference is that ncon_tenpy needs the sequence order while in ncon_GlenEvenbly it is an optional parameter with the increasing order as default.

**Comment by Jakob-Unfried** [comment]
indeed, the final transpose was missing in the implementation.

fixed by #196.
