### ISSUE TITLE
About (possibly inefficient) iDMRG sweep schedule function?

### ISSUE THREAD

**Issue by yeon-lee** [tenpy/tenpy#133]
If we look at the following function 

def get_sweep_schedule(self) in mps_common.py

for the case where bc = 'infinite' (iDMRG), the scheduling seems not working as I expected. For example, for conventional L=2 n=2 case, LP and RP get increased by four sites in every sweep, not two sites. This is not intuitive as for L=4 n=2 case, LP and RP get increased by four sites in every sweep as well.

What is the clear advantage of the current sweep schedule compared to the toy DMRG sweeping method in  (https://github.com/tenpy/tenpy/blob/main/examples/d_dmrg.py)?  This toy DMRG sweeping method does not have the problem I pointed out above for L=2 case, for example. 

Of course, this (maybe 'naive') approach has some problems. After the sweep, updated LP[0] and RP[L-1] acquire contributions not only from newly calculated A/B matrices, but also involves guess input B matrix. On the other hand, using the current DMRG sweep schedule, this does not happen.

I wonder whether there is some clear argument to prefer the current sweeping schedule.

**Comment by jhauschild** [comment]
I wouldn't really consider this a bug, it's just a slightly different meaning of what we call a "sweep". With L=2,n=2, you increase both the left and right environment by exactly 1 site after each bond update,  alternating between left and right - this is completely the same as in the toy code. The only difference is how many updates to do - in the toy code, we go up to `psi.n_bonds - 1 = psi.L -1`, while in TeNPy, we go up to `psi.L`. In other words, in TeNPy, when sweeping right, we continue a little bit further into the next unit cell before turning back sweeping left. It doesn't really matter that much, but it can actually help a little bit to update the bonds at the unit cell boundary (where the environments grow!) more, such that eventually we might even need less overall sweeps.
