### ISSUE TITLE
Request: Multiplying two iMPO's

### ISSUE THREAD

**Issue by ruochenma** [tenpy/tenpy#135]
Dear author,
   We need a function to do the product of two iMPO's and return a new iMPO, which means that the new iMPO obtained is physically equivalent to successively applying of the two operators. Especially we hope that the function can do the product of two infinite MPO's, which may appear when doing iDMRG.
   Thank you very much!

**Comment by Jakob-Unfried** [comment]
What would be the use case for this feature?

Such a combined operator would have a significantly larger bond dimension and working with it would be much more expensive.
If you want to apply it to an iMPS, you could just apply one iMPS after the other.
If you really wanted to work with a diagram that involves both iMPO, then keeping them factorized should allow more efficient contraction orders.

**Comment by jhauschild** [comment]
Since we don't plan to do this in the near tearm (and don't really see a good reason or even how to implement this), we'll close this for now.
