### ISSUE TITLE
TypeError: correlation_length() got an unexpected keyword argument 'charge_sector'

### ISSUE THREAD

**Issue by dillontliu** [tenpy/tenpy#14]
https://github.com/tenpy/tenpy/blob/1f1ac3f113d8f45a0347a5851d5ccb2bb0a84a5a/examples/xxz_corrlength.py#L63

I think 'charge_sector' shouldn't be passed to correlation_length(). Upon removing it, the example seems to be fine.

**Comment by jhauschild** [comment]
Thanks for pointing that out, commit 264cd807fbd9bcf6e9540749ae48173451b34cc2 should fix it
