### ISSUE TITLE
Request full width for tenpy docs

### ISSUE THREAD

**Issue by aaeberharter** [tenpy/tenpy#140]
On wide screen the tenpy-docs only cover about half of the screen, see image 
![tenpy](https://user-images.githubusercontent.com/13038167/125095261-4b8aac80-e0d4-11eb-9add-b63a11087d57.jpg)

In this issue https://github.com/readthedocs/sphinx_rtd_theme/issues/295 solutions are discussed. Apparently it is sufficient to add
```
.wy-nav-content {
   max-width: none;
}
```
in a css file.

**Comment by jhauschild** [comment]
Thanks for pointing this out! I was annoyed by the fixed width as well, but didn't know how to fix this.
