### ISSUE TITLE
Installation Failed of Tenpy using Conda on MacBook with M1 chip

### ISSUE THREAD

**Issue by rickypang0219** [tenpy/tenpy#150]
Hi, I encounter a problem when I am trying to install Tenpy into my MacBook with M1 chip(MacOS 12). I am trying to use conda for installing TeNPy. However, conda says that the following packages are not available from current channel. 

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - physics-tenpy

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


```

May I ask how can I solve this problem? I appreciate any comment.

**Comment by rickypang0219** [comment]
I solved my problem by using an alternative method. I downloaded the tar.bz2 file from [Anaconda website](https://anaconda.org/conda-forge/physics-tenpy/files) and run ``` conda install <path to tenpy tar.bz2>``` in terminal. This method seems work but I am still wondering how to use ```conda install --channel=conda-forge physics-tenpy``` directly.

**Comment by rickypang0219** [comment]
It seems that previous method ( by running ```conda install <path to tenpy tar.bz2>``` in terminal) does not work. I tried to use Jupyter in VS code and tenpy package have conflict with other packages such that the Jupyter notebook cannot be open properly.

**Comment by jhauschild** [comment]
That's because the M1 architecture requires a separte compilation. 
See [this section in the conda builds](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds)
and https://tenpy.johannes-hauschild.de/viewtopic.php?f=7&t=212.
Would you like to give it a shot and try the necessary steps?

**Comment by rickypang0219** [comment]
Thank you for your reply, Mr. Hauschild. I used another alternative method to install TeNPy which was using the built-in pip in conda. As I am new to conda, I did not know that I can use pip function in conda before. Now I try to use DMRG to find the ground state of Fermi Hubbard model and it works properly. I appreciate your help.

**Comment by AlexSchuckert** [comment]
> That's because the M1 architecture requires a separte compilation.
> See [this section in the conda builds](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds)
> and https://tenpy.johannes-hauschild.de/viewtopic.php?f=7&t=212.
> Would you like to give it a shot and try the necessary steps?

I just added it, let's see what happens...Did you have any more contact with people trying to compile on M1? Got mine today, first thing I did is installing tenpy haha

**Comment by AlexSchuckert** [comment]
[Here it is ](https://github.com/conda-forge/physics-tenpy-feedstock/pull/18)saying that four checks failed and they required your review, @jhauschild. I would do it myself, but I don't really know what to do.

**Comment by AlexSchuckert** [comment]
TeNPy actually runs fine if you compile it yourself. I just ran the test suite and it said "246 passed, 4 skipped in 59.87s". I have not yet tested performance compared to Intel, but I have put some effort into making numpy fast. If you are interested in my installation, [see this Medium post](https://alexaldo.medium.com/apple-silicon-m1-for-the-quantum-physicist-4f101ea99cf4).

**Comment by JRWSP** [comment]
I followed Alex's Medium post and successfully install native arm64 packages. They worked really fine. TeNPy just have to be compiled from source.  I did a benchmark by running `ExpMPOEvolution` of `MPS` and got slightly faster for the native version.
Showing in my progress bar
- x86-64 (Rosetta2) 33.72it/s. 
- arm64 (Native) 37.59it/s.

My device is MacBook M1 2020 16GB.

**Comment by Jakob-Unfried** [comment]
> That's because the M1 architecture requires a separte compilation. See [this section in the conda builds](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds)

It looks like somebody has done this by now, i.e. put `physics-tenpy` in the list to be ported on the feedstock repo.
conda forge reports migration of tenpy to osx-arm64 as complete on https://conda-forge.org/status/#armosxaddition.

However, it seems like silicon specific builds of tenpy are still not available from conda.
E.g. we do not see a `osx-arm64` specific installer on the [tenpy conda page](https://anaconda.org/conda-forge/physics-tenpy) and no arm64 specific wheels in the [files](https://anaconda.org/conda-forge/physics-tenpy/files).

That might be because we have not released in a long while, and in particular the last release v0.10 does not yet include the pyproject.toml ?

We should check again after the next release, I guess.

**Comment by JRWSP** [comment]
> > That's because the M1 architecture requires a separte compilation. See [this section in the conda builds](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds)
> 
> It looks like somebody has done this by now, i.e. put `physics-tenpy` in the list to be ported on the feedstock repo. conda forge reports migration of tenpy to osx-arm64 as complete on https://conda-forge.org/status/#armosxaddition.
> 
> However, it seems like silicon specific builds of tenpy are still not available from conda. E.g. we do not see a `osx-arm64` specific installer on the [tenpy conda page](https://anaconda.org/conda-forge/physics-tenpy) and no arm64 specific wheels in the [files](https://anaconda.org/conda-forge/physics-tenpy/files).
> 
> That might be because we have not released in a long while, and in particular the last release v0.10 does not yet include the pyproject.toml ?
> 
> We should check again after the next release, I guess.

Still not seeing `osx-arm64` for v.0.11 in the conda page, only `osx-64`

**Comment by Jakob-Unfried** [comment]
@JRWSP There are native wheels on conda now as well =)

**Comment by Jakob-Unfried** [comment]
Will close this as completed - tenpy can be installed on apple silicon device now.

@AlexSchuckert @JRWSP
If you use the native arm wheels, please let us know how well this works for you.
My hope is that you can now get a fast installation directly from conda forge without any of the more hacky steps.

**Comment by AlexSchuckert** [comment]
Awesome, thank you so much! I will try this soon.

Best,
Alex

**Comment by JRWSP** [comment]
The conda version now works perfectly on my M1 device. Thanks a lot for this!
