### ISSUE TITLE
[cite]

### ISSUE THREAD

**Issue by GuilleRom** [tenpy/tenpy#151]
R. Peña, V. M. Bastidas, F. Torres, W. J. Munro, G. Romero. Fractional resonances and prethermal states in Floquet systems,  https://arxiv.org/abs/2111.06949  

Please include it into the list of [papers using TeNPy](https://tenpy.readthedocs.io/en/latest/papers_using_tenpy.html)

**Comment by jhauschild** [comment]
Thanks for pointing it out!
