### ISSUE TITLE
[cite]

### ISSUE THREAD

**Issue by rgbmrc** [tenpy/tenpy#152]
I've used TeNPy in a recent work:  
Entanglement generation in (1+1)D QED scattering processes
https://arxiv.org/abs/2105.03445
https://doi.org/10.1103/PhysRevD.104.114501

Please include it into the list of [papers using TeNPy](https://tenpy.readthedocs.io/en/latest/papers_using_tenpy.html)

Thanks a lot for your work!

**Comment by jhauschild** [comment]
I have missed that in my last search, sorry. Thanks for pointing it out!
