### ISSUE TITLE
[cite] Quantum simulation of 2D antiferromagnets with hundreds of Rydberg atoms

### ISSUE THREAD

**Issue by aaeberharter** [tenpy/tenpy#162]
We used TeNPy in a recent work:  https://www.nature.com/articles/s41586-021-03585-1

Please include it into the list of [papers using TeNPy](https://tenpy.readthedocs.io/en/latest/papers_using_tenpy.html)

**Comment by jhauschild** [comment]
Thanks for pointing it out; it appears I missed it in the arxiv fulltext search - sorry!

It's an great paper, by the way - it's incredible what these guys can do with the Rydberg atoms, and you've provided excellent comparison data! Right now we're also working with that group :)

**Comment by aaeberharter** [comment]
Thanks for the kind words. In a sense you also participated in this project through tenpy ;). I wish you much success!
