### ISSUE TITLE
No module named 'tenpy'

### ISSUE THREAD

**Issue by Chapa1** [tenpy/tenpy#17]
Hello! 
I saved Tenpy at 'C:\TenPy' and created the variable 'PYTHONPATH' with the value 'C:\TenPy\tenpy'.
But when I launch Spyder and write 
import tenpy
print(tenpy.__version__)
It says: ModuleNotFoundError: No module named 'tenpy'

**Comment by jhauschild** [comment]
This is clearly an installation Problem, which you need to figure out yourself, sorry....

I think, you should set the PYTHONPATH variable to 'C:\TenPy' without the additional '\tenpy'.
As a further hint: In Spyder, you can mangage the PYTHONPATH variable vie the menu option Tools->PYTHONPATH Manager.
