### ISSUE TITLE
Wrong type of MPS.get_SL

### ISSUE THREAD

**Issue by pulkin** [tenpy/tenpy#170]
```
Traceback (most recent call last):
  ...
  File ".../main.py", line 134, in run_dmrg
    psi.canonical_form()
  File ".../tenpy/networks/mps.py", line 2814, in canonical_form
    return self.canonical_form_infinite(**kwargs)
  File ".../tenpy/networks/mps.py", line 2991, in canonical_form_infinite
    Gl = npc.tensordot(Kr.scale_axis(self.get_SL(i1)**2, 1), Kl, axes=['vR', 'vL'])
TypeError: unsupported operand type(s) for ** or pow(): 'Array' and 'int'
```
Installed from `pip`, mps is a no-thrills solution provided by infinite two-site DMRG.

**Comment by Jakob-Unfried** [comment]
I cant replicate this.
Also, at least since #326 the DMRG engine `run` can not return without calling `mixer_cleanup`,
so this should not happen anymore.

https://github.com/tenpy/tenpy/blob/0c5802ff10c9a10deabf64d5497bb7c66187d21f/tenpy/algorithms/mps_common.py#L737-L751
