### ISSUE TITLE
Undefined varaible in ground_state_search.OrthogonalExcitations (?)

### ISSUE THREAD

**Issue by yuchihe** [tenpy/tenpy#180]
see "self.results['ground_state_energy'] = E0"

E0 seems to be undefined.

**Comment by Jakob-Unfried** [comment]
It seems like [this commit](https://github.com/tenpy/tenpy/commit/64ee7a41827f0cf23f19b2cf363d7d8b322fcc67#diff-05de523b29605437841b7c95288a4feca15ca962a088353da3fe76f6f33ab83fR175) introduced the bug

**Comment by jhauschild** [comment]
actually, this was solved in another branch, excitation-science, see also #178.

The real issue is that the branches became a mess, and I need to sort out which branch contains what on top of what.... I'll try to do that asap, should have done that much earlier!
