### ISSUE TITLE
module 'tenpy.algorithms.tdvp' has no attribute 'TwoSiteTDVPEngine'

### ISSUE THREAD

**Issue by TheWorldYa** [tenpy/tenpy#188]
When I tried to run the example "e_tdvp.py", it turned out to "module 'tenpy.algorithms.tdvp' has no attribute 'TwoSiteTDVPEngine'". How can I fix this?

**Comment by TheWorldYa** [comment]
Can anybody help me?

**Comment by jhauschild** [comment]
The corresponding example works; it rather sounds like you have an issue with your installation.
Try to just open python interactively and run `import tenpy` and `tenpy.show_config()`. If that doesn't work, you didn't install TeNPy correctly. 
Follow the [installation instructions](https://tenpy.readthedocs.io/en/latest/INSTALL.html).

If you actually can import tenpy, but don't find `tenpy.algorithms.tdvp.TwoSiteTDVPEngine`, you likely have an old installation of tenpy that you need to update/uninstall first. You can see the location by just calling `import tenpy; print(repr(tenpy));`.

**Comment by TheWorldYa** [comment]
@jhauschild
Thank you for your reply, that's very helpful. By the way, may I ask you another question?  I'm wondering how to effectively convert an Haar-random state (an array of dimension 2^L) into a MPS in order to evolve it using TDVP or other methods. What modules do I need to use specifically?

**Comment by jhauschild** [comment]
You could convert it into an MPS, but you cannot truncate it without significant truncation error:
An old result by [Page](https://doi.org/10.1103/PhysRevLett.71.1291) showed that Haar random states have almost maximal entropy, at the central bond it's `S=L/2 log(d) - 1/2` (where the 1/2 is the deviation from the maximum and subleading compared to the volume law!).

So while you can convert it into an MPS (e.g. using [MPS.from_full](https://tenpy.readthedocs.io/en/latest/reference/tenpy.networks.mps.MPS.html#tenpy.networks.mps.MPS.from_full)), you will get an MPS with bond dimension growing exponentially with system size - which is not "efficient", you don't gain any speed-up compared to just brute-force exact diagonalizaiton.
