### ISSUE TITLE
iDMRG bookkeeping of energy

### ISSUE THREAD

**Issue by nobody95** [tenpy/tenpy#19]
Hi Johannes,

I am a new user of tenpy. I ran some iDMRG simulations and found that the energy converges rather slowly, while other measurables such as correlations and entanglement entropy converge much faster.
After looking into the library, I came to notice the following minor issue concerning the bookkeeping of energy in iDMRG procedure and I wonder if you would agree with me:
in tenpy.algorithms.dmrg.py, line 447:
` E = (Es[-1] - Es[0]) / (age[-1] - age[0])`
should perhaps be changed to:
` E = (Es[-1] - Es[-2]) / (age[-1] - age[-2])`
to get rid of the boundaries, which are not well-optimized.

Thanks for the nice package, by the way.

**Comment by jhauschild** [comment]
Thank you very much for pointing that out and even suggesting the corrected code!
The `age[-2]` is just one bond update before, so this it's also not the correct thing to use, but
the actual fix ae900e3e4dfaa097b58e67ea0cdaa0a3153f96b6 looks quite similar.
Thanks again!
