### ISSUE TITLE
Square lattice with the nearest-neighbor couplings

### ISSUE THREAD

**Issue by TheWorldYa** [tenpy/tenpy#194]
I'm constructing a square lattice where a unit cell consists of four sites. I'm wondering how to add intra couplings and inter couplings conveniently, make sure they are different constants to form a tetramer. Can anyone help me, please?

**Comment by Jakob-Unfried** [comment]
For general reading, have a look at the [models section](https://tenpy.readthedocs.io/en/latest/intro/model.html#the-couplingmodel-general-structure) of the introduction.

If i understand the model you want to implement correctly, the easiest way should be to use a `Square` lattice, and use an array as the coupling strength, as documented in [`add_coupling`](https://tenpy.readthedocs.io/en/latest/reference/tenpy.models.model.CouplingModel.html#tenpy.models.model.CouplingModel.add_coupling).
Alternating the inter and intra coupling (roughly `[[t_inter, t_intra] * (Lx // 2)] * Ly` for the horizontal couplings) should do what you want.

For future questions that do not warrant changes to the code or documentation, please use the [forum](https://tenpy.johannes-hauschild.de/)
