### ISSUE TITLE
Poor performance in SLURM job array

### ISSUE THREAD

**Issue by jkidd1** [tenpy/tenpy#208]
I need to run 100 DMRG calculations on a custom model, each with a different set of model parameters. I will not include the Tenpy code here because it is very similar to the example `01_dmrg.ipynb`, but I can share it if needed. My usual workflow for this kind of problem is to run each calculation in a separate folder in parallel using a SLURM job array. Here is my SLURM script:

```
#!/bin/bash
#SBATCH -J dmrg
#SBATCH -o output.%j
#SBATCH -e error.%j
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH --array=1-100
#SBATCH -c 1 # one core per task

echo $SLURM_ARRAY_TASK_ID
subfolder=$(awk "NR==$SLURM_ARRAY_TASK_ID" job.list)
echo $subfolder
cd ../calculations/$subfolder

date
srun python main.py
date
```

When I do this, I notice that the performance is very bad. For reference, if I submit the first job by itself (i.e., not using an array), it finishes in under one minute. However, in the array, the job is still running `TwoSiteDMRGEngine(psi, Model, dmrg_params)` after ten minutes. Any idea what is going on here?

**Comment by Jakob-Unfried** [comment]
I am not too familiar with SLURM, but i can imagine two possible explanations:
- The single jobs is using more cores than the individual tasks of the array. Look at the CPU usage of the jobs while they run. For controlling the number of cores see [FAQ](https://tenpy.readthedocs.io/en/latest/troubleshooting.html#troubleshooting-and-faq).
- The job array is setting up your python environment differently, which could cause the comiled tenpy to not be loaded or a different numpy binary to be linked. Look at the output of `tenpy.show_config()` for a single job vs a job array.

**Comment by jkidd1** [comment]
My apologies for not following up! It was indeed an issue with my own OpenMP configuration. Basically, I didn't realize that `export OMP_NUM_THREADS=1` needs to be set in the SLURM script if we want to run tenpy itself in serial and parallelize jobs across cores according to the SLURM array.
