### ISSUE TITLE
Multiple problems with AKLT state generation

### ISSUE THREAD

**Issue by kattemolle** [tenpy/tenpy#210]
# The issues

There are multiple problems with `tenpy.models.aklt.AKLTChain.psi_AKLT()` (first implemented in the latest version, v0.10.0), which is supposed to return an MPS representing the ground state of the AKLT model. 

- A minor point it that the function's documentation does not state what this method returns. (It returns an MPS.)
- The major point is that there are errors in the code. So the function cannot be run. (This is the bug.)
- Another point is that the implementation of this function can be implemented much more efficiently (in terms of lines of code and conceptually, not runtime.)

# Code
The code of tenpy.models.aklt.AKLTChain.psi_AKLT() is as follows (v0.10.0)

```python
    def psi_AKLT(self):
        """Initialize the chi=2 MPS which is exact ground state of the AKLT model."""
        # build each B tensor of the MPS as contraction of
        #    --sR  sL--
        #       |  |
        #       proj
        #         |
        #
        # where  SL--SR forms a singlet between neighboring spin-1/2,
        # and projS1 is the projector from two spin-1/2 to spin-1.
        # indexing of basis states:
        # spin-1/2: 0=|m=-1/2>, 1=|m=+1/2>;  spin-1: 0=|m=-1>, 1=|m=0> 2=|m=+1>
        sL = np.sqrt(0.5) * np.array([[1., 0.], [0., -1.]]) # p2 vR
        sR = np.array([[0., 1.], [1., 0.]]) # vL p1
        proj = np.zeros([3, 2, 2]) # p p1 p2
        proj[0, 0, 0] = 1.  # |m=-1> = |down down>
        proj[1, 0, 1] = proj[1, 1, 0] = np.sqrt(0.5)  # |m=0> = (|up down> + |down, up>)/sqrt(2)
        proj[2, 1, 1] = 1.  # |m=+1> = |up up>
        B = np.tensordot(sR, proj, axes=[1, 1]) # vL [p1], p [p1] p2
        B = np.tensordot(B, sL, axes=[2, 0]) # vL p [p2], [p2] vR
        B = B * np.sqrt(4./3.)  # normalize after projection
        B = B.transpose([1, 0, 2]) # p vL vR
        S = np.sqrt(0.5) * np.ones([2])
        # it's easy to check that B is right-canonical:
        BB = np.tensordot(B, B.conj(), axes=[[0, 2], [0, 2]])
        assert np.linalg.norm(np.eye(2) - BB) < 1.e-14

        L = self.lat.N_sites
        Bs = [B] * L
        Ss = [S] * (L + 1)

        spin1 = self.lat.unit_cell[0]
        legL = None  # default
        if self.lat.bc_MPS == 'finite':
            # project onto one of the two virtual states on the left/right most state.
            # It's a ground state whatever you choose here,
            # but we project to different indices to allow Sz convservation
            # and fix overall Sz=0 sector
            Bs[0] = Bs[0][:, :1, :]
            Bs[-1] = Bs[-1][:, -1:, :]
            Ss[0] = Ss[-1] = np.ones([1.])
        elif spin1.conserve in ['Sz', 'parity']:
            chinfo = spin1.leg.chinfo
            legL = npc.LegCharge.from_qflat(chinfo, [[0], [2]])
        return MPS.from_Bflat(self.lat.mps_sites(),
                              Bs,
                              bc=self.lat.bc_MPS,
                              permute=True,
                              form='B',
                              legL=legL)
```
**Error traceback**

```
[Traceback]
...
  File "/opt/miniconda3/lib/python3.9/site-packages/tenpy/models/aklt.py", line 103, in psi_AKLT
    Ss[0] = Ss[-1] = np.ones([1.])
  File "/opt/miniconda3/lib/python3.9/site-packages/numpy/core/numeric.py", line 204, in ones
    a = empty(shape, dtype, order)
TypeError: 'float' object cannot be interpreted as an integer
```
So the culprit seems to be `Ss[0] = Ss[-1] = np.ones([1.])`, which makes sense since np.ones expects a list or tuple of ints. 

However, upon further inspection `Ss[0] = Ss[-1] = np.ones([1.])` is not even needed. Nor are `S = np.sqrt(0.5) * np.ones([2])` and `Ss = [S] * (L + 1)`. These variables are defined but never used. 

# Sugested corrections
I'm not yet confident enough with TeNPy to submit a pull request. However, I think the following edits would fix the code. 

- Remove `Ss[0] = Ss[-1] = np.ones([1.])`,`S = np.sqrt(0.5) * np.ones([2])` and `Ss = [S] * (L + 1)`.
- Change `Bs[-1] = Bs[-1][:, -1:, :]` to `Bs[-1] = Bs[-1][:, :, -1:]`

# More transparent implementation
Although the current implementation (after fixing) is fine, it is more involved that needed. For the AKLT chain the `'B'` tensors are known and hence the MPS can be defined _directly_ by specifying the `'B'` operators directly. There is no need to work with singlets and projections. 

The `'B'` operators are all given by $B=[B^+,B^0,B^-]$, with $B^+=\sqrt{2/3}\sigma^+, B^0=-\sqrt{1/3}\sigma^z, B^-=-\sqrt{2/3}\sigma^+$. (This definition of $B$ would define the tensor with legs `['p','vL','vR']` and is in right canonical form (incidentally it is also in left canonical form). See, e.g., https://en.wikipedia.org/wiki/AKLT_model . For finite boundary conditions, the left and rightmost virtual leg can be projected out, as in the fixed code above.

**Comment by jhauschild** [comment]
Indeed, the motivation behind the lengthier code is that you can actually see where things come from: you could just multiply the (small) matrices by hand and only have the final Bs, but in the given code you can really see where these matrices come from. The code is directly following the construction outlined in Fig 3 (d-e) of the (TeNPy lecture **notes](https://arxiv.org/abs/1805.00055).

That's also the reason why I split the singlet into two tensors: in general, you could just write one tensor, and the other one is a trivial identity, but it's easier to connect the sR and sL tensors to the dots in the standard AKLT figure.

**Comment by Jakob-Unfried** [comment]
The tests check that the resulting state is a groundstate of the AKLT hamiltonian, so it should be correct.

Even in a canonical form, the MPS tensors are not unique. You can still have arbitrary unitary transformations on the virtual indices. So just because the B tensors do not agree does not mean that the states are different or that either one is "wrong".
