### ISSUE TITLE
Incorrect variable name in MPS.expectation_value_terms_sum

### ISSUE THREAD

**Issue by tomohiro-soejima** [tenpy/tenpy#215]
The function `MPS.expectation_value_terms_sum` contains the following line:

https://github.com/tenpy/tenpy/blob/e24bd72129d3e66629ee47e5ec41295c9953610e/tenpy/networks/mps.py#L2417

However, `TermList` objects do not have an attribute `prefactors`. Instead, it has `strength` (https://tenpy.readthedocs.io/en/latest/reference/tenpy.networks.terms.TermList.html#tenpy.networks.terms.TermList).

Accordingly, I believe the line should be modified to say `strength` instead of `prefactors`.

Thanks!

**Comment by jhauschild** [comment]
Thanks for pointing the bug out, Tomo!
As mentioned in the commit message, I added a test and fixed yet another typo (undefined variable name) the line below.
I've added you as co-author, since you already pointed out the fix.

**Comment by tomohiro-soejima** [comment]
Thanks for your prompt fix, and glad I could help!
