### ISSUE TITLE
BUG in QRBasedTEBDEngine

### ISSUE THREAD

**Issue by OliverLunt** [tenpy/tenpy#244]
I think there is a small bug in QRBasedTEBDEngine. Attempting to use a value of `cbe_expand_0` which is different from `cbe_expand` results in the error

```
File ~/mambaforge/envs/tenpy-experimental/lib/python3.11/site-packages/tenpy/algorithms/tebd.py:646, in QRBasedTEBDEngine._expansion_rate(self, i)
    643 if chi_max is None:
    644     raise ValueError('Need to specify trunc_params["chi_max"] in order to use cbe_expand_0.')
--> 646 chi = min(self.get_SL(i).shape)
    647 return max(expand_0 - chi / chi_max * (expand_0 - expand), expand)

AttributeError: 'QRBasedTEBDEngine' object has no attribute 'get_SL'
```

Changing the offending line 646 to
```
chi = min(self.psi.get_SL(i).shape)
```
fixes the issue.

Anyway, thanks for adding this great feature!

**Comment by Jakob-Unfried** [comment]
Hi, thanks for the report and I am happy to see interest in the new engine.
I pushed a fix to #245 , to be merged soon.
