### ISSUE TITLE
BUG: ExpMPOEvolution doesn't check explicit_plus_hc flag.

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#265]
I got a report from @Jack-Kemp and friends, who were trying to run some time evolution starting from a ground state obtained with DMRG, ramping up some parameter in H with the `TimeDependentExpMPOEvolution`.
They saw very inconsistent behaviour, where the energy of the state just went up with time, independent of how fast they ramped up the parameter.

It turned out that they used the `explicit_plus_hc=True` parameter in the Model. This parameter allows to just represent a non-hermitian part of H, indicating that the full H is `H_MPO + hc(H_MPO)` . The result is a smaller MPO bond dimension, which can save memory (when the MPO environments are the dominant part in RAM). DMRG is designed to work with that and uses a small wrapper for the effective Hamiltonian for `explicit_plus_hc=True`, that ensures this explicit sum is performed.

The error started, when they tried to do time evolution on top - the MPO functions `MPO.make_U_I()` and `make_U_II` just ignore the explicit_plus_hc flag - assuming that the MPO represented is the full H. Since H is not hermition, the resulting `U = exp(i H dt)` is no longer unitary, and MPO evolution just converges to a completely wrong steady state (as far as I can see from the plots they sent me).

**Suggested fix** 
I think the correct behaviour should be that `MPO.make_U_I,II()` just raises an Error when the `explicit_plus_hc=True` flag is set.

In principle, they could also try to add the h.c. part, but that would result in a larger MPO bond dimension than necessary, and a following MPO compression is complicated and error-prone - it's much easier to just generate the full H from the beginning when setting up the model.

**Comment by jhauschild** [comment]
To be clear, the best solution is to just disable the `explicit_plus_hc` flag in the model when you want to use the ExpMPOTimeEvolution.

**Comment by Jack-Kemp** [comment]
> To be clear, the best solution is to just disable the `explicit_plus_hc` flag in the model when you want to use the ExpMPOTimeEvolution.

And add it explicitly the hermitian conjugate terms, yes?

**Comment by Jack-Kemp** [comment]
Many thanks for sorting this out @jhauschild ! I agree a warning seems the best way to go. Are there any other functions to be wary of when using explicit_plus_hc ?
