### ISSUE TITLE
Hofstadter model symmetric gauge fails on finite MPS

### ISSUE THREAD

**Issue by Lschoon** [tenpy/tenpy#28]
I have been working om some more extensive nosetests for the Hofstadter model and noticed the following problem. When setting the gauge to `'symmetric'` and `bc_MPS` to `'finite'` simultaneously, the following error arises. Note that:
- `phi = (1, 9)`, `Lx = 9`, `Ly = 9`.
- Thus, the magnetic unit cell is 3x3, giving a tiling of 3 MUCs in both lattice dimensions.
- Setting phi = 1/3 and a landau gauge (which also gives 3 MUCs in one of the lattice dimensions) does not result in an error.
- The 8 (rather than 9) in the raised `ValueError: incomensurate len for tiling from 3 to 8` is due to the finite b.c.

It seems like either this case should work, or the phi = 1/3 , `bc_MPS = 'finite'` case should result in the same error.

```
ERROR: test_model_hofstadter.test_HofstadterFermions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leon/.conda/envs/idp3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/leon/tenpy/tests/test_model_hofstadter.py", line 25, in test_HofstadterFermions
    'mu':[0, 0.123]
  File "/home/leon/tenpy/tests/test_model.py", line 68, in check_general_model
    M = ModelClass(params)
  File "/home/leon/tenpy/tenpy/models/hofstadter.py", line 168, in __init__
    CouplingMPOModel.__init__(self, model_params)
  File "/home/leon/tenpy/tenpy/models/model.py", line 1172, in __init__
    self.init_terms(model_params)
  File "/home/leon/tenpy/tenpy/models/hofstadter.py", line 204, in init_terms
    self.add_coupling(hop_x, 0, 'Cd', 0, 'C', dx)
  File "/home/leon/tenpy/tenpy/models/model.py", line 747, in add_coupling
    strength = to_array(strength, strength_shape)  # tile to correct shape
  File "/home/leon/tenpy/tenpy/tools/misc.py", line 64, in to_array
    a.shape[i], shape[i]))
ValueError: incomensurate len for tiling from 3 to 8
```

Code to reproduce this error is in https://github.com/Lschoon/tenpy/tree/dev.

**Comment by jhauschild** [comment]
Took me some time to figure this out, but I think I found the problem:

in the symmetric gauge, it should be
```python
        hop_x = -Jx * np.exp(-1.j * (phi/2) * np.arange(my)[np.newaxis, :])
        hop_y = -Jy * np.exp(1.j * (phi/2) * np.arange(mx)[:, np.newaxis])
```
instead of
```
        hop_x = -Jx * np.exp(-1.j * (phi/2) * np.arange(my)[:, np.newaxis])
        hop_y = -Jy * np.exp(1.j * (phi/2) * np.arange(mx)[np.newaxis, :])
``

**Comment by jhauschild** [comment]
The landau gauge is fine, because the the hopping in y direction depends on x, and the shape for that is independent of the boundary conditions in x-direction (set by `bc_MPS`).

@Lschoon I leave it to you to fix this issue with your other modifications and will close the pull request as soon as we merged the changes. Many thanks in advance!

**Comment by Lschoon** [comment]
That's it! I copied it over wrongly from the Landau gauges; with this change it works (and the gauges are consistent between them, which is nice...)

Doing some last cleanup, pull request will follow shortly.

**Comment by jhauschild** [comment]
Thank you very much!
