### ISSUE TITLE
Ground State Search and (eventually) Time Evolution for PEPS

### ISSUE THREAD

**Issue by nheinsdorf** [tenpy/tenpy#280]
I want to find the ground state of a spin Hamiltonian and encode it in an infinite Projected Entangled Pair State (iPEPS). I'd also be interested in time evolving that state eventually. 
As far as I can tell, there is so far no (published) implementation of PEPS. 
I think especially the `isometric` form of PEPS as shown in this work 
https://arxiv.org/abs/1902.05100
looks like it would be an extremely useful addition to the tenpy library. 

I'd be happy to help with the implementation. I guess the first thing to do would be to create a PEPS class, similar to the MPS class and then start to add functionality for contraction. 
I am familiar with the basic structure, but I'm not sure how tenpy's functionality of conserving charges etc would be implemented.

**Comment by Jakob-Unfried** [comment]
Hi Niclas,

Thanks for the interest!

I have started with a PEPS class in #228.
It is supposed to cover both finite and infinite PEPS, like in the MPS case.
Isometric PEPS should probably be a subclass.

There is an effort to include the PEPS codes that we have floating around in tenpy, but it is moving slowly.
This will include contraction and gradient-based optimization of finite PEPS from me and the isometric PEPS
codes form ShengHsuan, Sajant, ...
At least for me, I can not make this it a priority right now....

If we want to work on PEPS implementations collaboratively, i suggest we use `peps` as a main branch and work on individual per-feature subbranches that we merge often.

If you want to use iPEPS, the first step would probably be to implement routines for the infinite environment, either CTMRG or via iMPS. Those routines should probably be implemented in a class that uses this algorithm, similar to e.g. the DMRG engine class(es).
The PEPS class in #228 should have most/all features you need for that.

As long as you use the functions from `tenpy.linalg.np_conserved`, e.g. `tensordot`, `svd`, ...
you do not need to worry about the charges when implementing these algorithms.
The only non-trivial interaction with the charges is when you create new tensors (`Array` objects).
But if you assume for now that the algorithm gets a PEPS instance that already has tensors, you can
just work with them, regardless of what their charges are.

Let us move further discussion to the PR #228 =)
