### ISSUE TITLE
`MPS.canonical_form` calls `MPS.canonical_form_infinite1` instead of `MPS.canonical_form_infinite2`

### ISSUE THREAD

**Issue by tomohiro-soejima** [tenpy/tenpy#283]
Hi!

I noticed the documentation of `MPS.canonical_form` is not consistent with the actual code. I assume the code needs to be changed to call `MPS.canonical_form_infinite2`. 
https://github.com/tenpy/tenpy/blob/3db87cb75d2531a9b6a6bb6f7b14ae2e2b714368/tenpy/networks/mps.py#L3281-L3290

Thanks

**Comment by Jakob-Unfried** [comment]
Thanks for the report.

For backwards compatibility, we should keep the implementation the same and adjust the docstring instead.
Will be fixed by #285.
