### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by meandmytram** [tenpy/tenpy#284]
I think there must have been a typo in the documentation [here](https://github.com/tenpy/tenpy/blob/main/doc/intro/npc.rst?plain=1#L35). Seems like it should say (like :math:`**S^z**` for Sz conservation) instead of (like :math:`**S^x**` for Sz conservation), thanks!

**Comment by Jakob-Unfried** [comment]
thanks for reporting typos!

Here, however, the docs are corrects as is.

The point is that if you enforce Sz conservation,  you can not write down the Sx operator.

One way to see this:
We usually include a factor two such that values of the conserved charge Q=2*Sz are integer. 
Now Sx is the sum of the raising operator S+ with total charge `qtotal=+2` and the lowering operator S- with total charge -2.
This means that Sx has no well defined total charge and therefore we can not write Sx as an `tenpy.linalg.np_conserved.Array`.

**Comment by meandmytram** [comment]
Oh I see, it totally makes sense, thanks a lot for the explanation! @Jakob-Unfried
