### ISSUE TITLE
Initializing BosonSite to a thermal state

### ISSUE THREAD

**Issue by ntrqpy** [tenpy/tenpy#286]
Hi,
First of all, thank you so much for building this awesome package. 
Could you please provide instructions on how to initialize `BosonSite` to a thermal state?
I found that `from_lat_product_state` 's argument `p_state` can take a list of 1D arrays, so my guess is that each 1D-array element can be used to specify the initial state of each `BosonSite`.
However, from the documentation and code, it wasn't clear to me exactly how each 1D array is converted to a bosonic state. Should I just naively input the diagonal of the thermal state's density matrix? 
Thanks again!

**Comment by jhauschild** [comment]
What exactly do you mean with a "thermal state"?
I'd usually write a thermal *density matrix* `rho = exp(-beta H ) / Z` with `Z = tr(exp(-beta H)`, but MPS typically represent *pure states*.
One common approach (besides e.g. METTS, which is currently not implemented in TeNPy) would be a purification of the density matrix with the `tenpy.networks.purification_mps.PurificationMPS`.
There's some basic examples in `examples/purification.py`.

The idea is to start at infinite temperature and then cool down to finite temperatures with imaginary time evolution.
There is a subtlety with bosons, however: at infinite temperature (`PurificationMPS.from_infiniteT`), the boson number can be anything (in the grand canonical ensemble), giving you an infinite-dimensional local Hilbert space, while MPS need to truncate to finite boson numbers to be able to represent it with finite-dimensional tensors....
If you work with finite systems, you can get around this by using a canonical ensemble instead (`PurificationMPS.from_infinite_T`), I think things should work in principle (assuming that you have a particle-conserving H).

**Comment by ntrqpy** [comment]
Thanks for this kind explanation! I am new to these simulations and I wasn't aware that MPS should represent pure states.
