### ISSUE TITLE
Segmentation fault on Ubuntu 18.04

### ISSUE THREAD

**Issue by JerryChen97** [tenpy/tenpy#31]
```
root@jerry-Lenovo:~/TeNPy/examples# python3 test_tdvp.py 
parameter 'lattice'='Chain' for SpinChain
parameter 'bc_MPS'='finite' for SpinChain
parameter 'S'=0.5 for SpinChain
parameter 'conserve'='Sz' for SpinChain
parameter 'L'=10 for SpinChain
parameter 'Jx'=1.0 for SpinChain
parameter 'Jy'=1.0 for SpinChain
parameter 'Jz'=1.0 for SpinChain
parameter 'hx'=0.0 for SpinChain
parameter 'hy'=0.0 for SpinChain
parameter 'hz'=0.0 for SpinChain
parameter 'muJ'=0.0 for SpinChain
['down', 'up', 'up', 'down', 'up', 'up', 'up', 'up', 'up', 'up']
parameter 'start_time'=0 for TDVP
parameter 'dt'=0.01 for TDVP
parameter 'trunc_params'={'chi_max': 50, 'svd_min': 1e-10, 'trunc_cut': None} for TDVP
Segmentation fault (core dumped)
```

I just successfully installed TeNPy on my Ubuntu 18.04 and began to test the examples.
However, I could not pass the nosetests and always came across a strange segmentation fault after a series of dots indicating successfully passing. Then I turned to the examples folder and ran the .py files one by one and found that if I ran test_tdvp.py then it would definitely exit with a segmentation fault indicating dumped cores. From the printing results, it seems that this happens immediately after passing parameters to one certain function in TDVP.
Did anyone run into this error before?

Here is my configuration:
`>>> print(tenpy.__full_version__)
tenpy v0.3.0-371-gc7bce6d using 
python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
numpy 1.16.2, scipy 1.2.1`

**Comment by jhauschild** [comment]
Thanks for the report!
Segmentation faults sound like problems caused by the Cython parts. I assume you called `./compile.sh`, right?
Just to be sure, does the error occur if you don't compile (call `bash cleanup.sh` to remove the compiled binaries)?
Did you update or start with a fresh installation?

Also, if you run the nosetests, can you please call it with `-v`, i.e. `nosetests -v` to see which of the tests fails? Does `nostests -v test_np_conserved.py` work?

**Comment by JerryChen97** [comment]
> Thanks for the report!
> Segmentation faults sound like problems caused by the Cython parts. I assume you called `./compile.sh`, right?
> Just to be sure, does the error occur if you don't compile (call `bash cleanup.sh` to remove the compiled binaries)?
> Did you update or start with a fresh installation?
> 
> Also, if you run the nosetests, can you please call it with `-v`, i.e. `nosetests -v` to see which of the tests fails? Does `nostests -v test_np_conserved.py` work?

Yes indeed I compiled Cython parts...

(Unfortunately, not long after the segmentation faults my laptop broke down for several days and finally I re-installed the system cleaning all the data. So I am not sure whether it will happen again and will try it once more later when I am available...)

**Comment by jhauschild** [comment]
does the problem persist?

**Comment by JerryChen97** [comment]
Ah sorry for such a long delay... I have been busy doing my mid-term defending these days. I will try it again by the end of tomorrow.

**Comment by JerryChen97** [comment]
Yeah it passed the test for tdvp~ No more segmentation fault
