### ISSUE TITLE
feature: add more consistency and error checks

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#314]
With Frank Pollmann and @p-thoma, we discussed today that we should add more consistency / error checks of reasonable parameters, and print big, fat warnings or even make it opt-in (by manually overriding threshold parameters) to keep running in certain instances.

Let me list a couple of examples, the list should probably be extended when implementing this:

- [x] Cylinder DMRG with way too large Ly
- [x] too large truncation errors e.g. in variational algorithms like DMRG
- [x] too large truncation errors during time evolution should stop the evolution
- [x] too large time steps for trotterization etc
- [x] Excessive use of prediction for spectral function post-processing
- [ ] spectral function: gaussian windowing too blurry? not enough t points for meaningful fourier trafo?
- [ ] there's probably more things we should check, think about what else.

**Comment by Jakob-Unfried** [comment]
@p-thoma can you do a check on the time in spectral function following the pattern in #364?

**Comment by p-thoma** [comment]
@Jakob-Unfried does it make sense to include a `consistency_check` call in `TimeEvolutionAlgorithm.run` (directly after 
dt is read out) ? In this way one could always warn for too large `dt` when performing a time evolution? Or move smth. like that into `Simulation.run` ?

**Comment by Jakob-Unfried** [comment]
> @Jakob-Unfried does it make sense to include a `consistency_check` call in `TimeEvolutionAlgorithm.run` (directly after dt is read out) ? In this way one could always warn for too large `dt` when performing a time evolution? Or move smth. like that into `Simulation.run` ?

I decided not to, because we only need to check for small time steps if the time evolution is trotterized, and there could be evolutions which have exact evolution operators. In fact, `RandomUnitaryEvolution` is one such case

**Comment by p-thoma** [comment]
> > @Jakob-Unfried does it make sense to include a `consistency_check` call in `TimeEvolutionAlgorithm.run` (directly after dt is read out) ? In this way one could always warn for too large `dt` when performing a time evolution? Or move smth. like that into `Simulation.run` ?
> 
> I decided not to, because we only need to check for small time steps if the time evolution is trotterized, and there could be evolutions which have exact evolution operators. In fact, `RandomUnitaryEvolution` is one such case.
> 
> So there currently are checks for large dt only where trotterization is actually performed, i.e. in build_U for TEBD and for MPOEvolution

Ok thanks! I see now why this is done in `calc_U` :)

**Comment by jhauschild** [comment]
Can one of you please add a similar check in TDVP for dt <= 1.?
Also, I think in the doc string of `consistency_check` we should add a big, fat disclaimer
```
.. note ::
  Obviously, the fact that we do consistency checks  like time steps ``dt < 1.`` does not mean that your resoults are likely to be converged for any choice of ``dt < 1`` ! Instead, you will likely have to choose a value much smaller than the threshold, 
and it is *your* responsibility as a user to ensure that you are in fact converged in every of the paremters.
``

**Comment by Jakob-Unfried** [comment]
agree with both =)
i can do it tomorrow

**Comment by Jakob-Unfried** [comment]
I am sure we do not have a complete set of checks, but we went through the list and established a pattern for these kinds of checks, so Ill close this.
