### ISSUE TITLE
`preserve_none` is not implemented for engines

### ISSUE THREAD

**Issue by 4psireal2** [tenpy/tenpy#319]
**Describe the bug**

1. Default value of  `preserve_norm` is None (see [doc](https://github.com/tenpy/tenpy/blob/41dea7f267dbafd9cd94cfe9ceee015995cf12aa/tenpy/algorithms/algorithm.py#L359C43-L359C56)) and not False (see [code](https://tenpy.readthedocs.io/en/latest/reference/tenpy.algorithms.algorithm.TimeEvolutionAlgorithm.html#tenpy.algorithms.algorithm.TimeEvolutionAlgorithm))
2. `preserve_norm` in `TimeEvolutionAlgorithm` is not passed to engine (for ex: [TEBD](https://github.com/tenpy/tenpy/blob/main/tenpy/algorithms/tebd.py))

**Minimal example or code extract**
I'm implementing quantum jump method (Ref: (Paper)[https://www.phys.ens.fr/~dalibard/publi3/osa_93.pdf]). I used `TEBDEngine` to do one-time-step evolution of the wavefunction using a non-Hermitian Hamiltonian (see Eq.11 in [Paper](https://www.phys.ens.fr/~dalibard/publi3/osa_93.pdf)). I expect the norm to drop after the evolution but it did not. This is the model:
```
class QCPModel(CouplingModel, MPOModel, NearestNeighborModel):
    """
    Implementation of part 1 in Section 2B
    """

    def __init__(self, params):
        L = params.get('L')
        omega = params.get('omega')
        gamma = params.get('gamma')
        bc_MPS = params.get('bc_MPS', 'finite')

        site = SpinHalfSite(conserve='None')  # no conserved quantities

        # Add operators to sites
        sigmax = np.array([[0, 1], [1, 0]])
        number_op = np.array([[0, 0], [0, 1]])
        annihilation_op = np.array([[0, 1], [0, 0]])
        site.add_op('sigmax', sigmax)
        site.add_op('number_op', number_op)
        site.add_op('annihilation_op', annihilation_op)

        oned_lattice = Chain(L=L, site=site, bc='open', bc_MPS=bc_MPS)

        CouplingModel.__init__(self, oned_lattice)
        for i in range(L - 1):
            self.add_coupling_term(strength=omega, i=i, j=i + 1, op_i='sigmax', op_j='number_op', plus_hc=False)
            self.add_coupling_term(strength=omega, i=i, j=i + 1, op_i='number_op', op_j='sigmax', plus_hc=False)

        for i in range(L):
            self.add_onsite_term(strength=-gamma * 1j / 2, i=i, op='number_op')

        # generate MPO for DMRG
        MPOModel.__init__(self, oned_lattice, self.calc_H_MPO())

        # generate H_bond for TEBD
        NearestNeighborModel.__init__(self, oned_lattice, self.calc_H_bond())
```
Here is the output
```
Norm of initial state: 1.0
TEBDEngine: subconfig 'trunc_params'=Config(<2 options>, 'trunc_params')
TEBDEngine: reading 'dt'=0.05
TEBDEngine: reading 'N_steps'=3
TEBDEngine: reading 'preserve_norm'=None
Calculate U for {'order': 2, 'delta_t': 0.05, 'type_evo': 'real', 'E_offset': None, 'tau': 0.05}
trunc_params: reading 'chi_max'=350
trunc_params: reading 'svd_min'=1e-12
--> time=0.150, max(chi)=16, max(S)=0.29338, avg DeltaS=1.0562e-01, since last update: 0.0s
Norm of state after 1 time step evolution without jump: 1.0
Norm diff: 0.22360679774997894
```

**Solution?**
Is there a quick modification of the `TEBDEngine`  (in [code](https://github.com/tenpy/tenpy/blob/main/tenpy/algorithms/tebd.py)) for this purpose? I tried to modify `update_bond` and `update_bond_imag` (see below), but the norm is still 1 after the evolution. How can I handle this issue?
```
U, S, V, trunc_err, renormalize = svd_theta(theta,
                                                    self.trunc_params,
                                                    [self.psi.get_B(i0, None).qtotal, None],
                                                    inner_labels=['vR', 'vL'])

S *= renormalize ## TODO: new change

# B_L /= renormalize  # re-normalize to <psi|psi> = 1
# self.psi.norm *= renormalize
```

**Comment by Jakob-Unfried** [comment]
Hi!
The documentation does indeed match the code.
As you can see, `None` is replaced by the proper default in the next lines:

https://github.com/tenpy/tenpy/blob/41dea7f267dbafd9cd94cfe9ceee015995cf12aa/tenpy/algorithms/algorithm.py#L359-L361

Could you share your entire minimal code? In particular the part that initializes and starts the TEBD engine?

**Comment by Jakob-Unfried** [comment]
Note also that `preserve_norm` does not need to be passed to the concrete engines.
The way this works is that any engine that performs the time evolution accumulates the norm change into `MPS.norm`.
Then, if `preserve_norm=True`, the `MPS.norm` is simply overridden by `TimeEvolutionAlgorithm.run_evolution`:

https://github.com/tenpy/tenpy/blob/03b259afae5a4caea11d5d6389a7476583ddcb5f/tenpy/algorithms/algorithm.py#L275-L276

**Comment by 4psireal2** [comment]
Many thanks for the answer! I think it would be more straighforward if `preserve_norm` can only take on `bool` values. So something in this direction, perhaps?

preserve_norm = self.options.get('preserve_norm', False)
if preserve_norm is False:  # default: do not preserve norm for real time evolution
	preserve_norm = not np.iscomplex(dt)
else:
        old_norm = self.psi.norm

> Hi! The documentation does indeed match the code. As you can see, `None` is replaced by the proper default in the next lines:
> 
> https://github.com/tenpy/tenpy/blob/41dea7f267dbafd9cd94cfe9ceee015995cf12aa/tenpy/algorithms/algorithm.py#L359-L361
> 
> Could you share your entire minimal code? In particular the part that initializes and starts the TEBD engine?

**Comment by Jakob-Unfried** [comment]
Please note that the purpose of minimal code examples is to be both complete (a script that can be run directly without modifying anything else and shows the issue) and minimal (leaving out anything unrelated).

Is there any chance you are starting with a spin up product state as `psi_t`?
That state is a zero-energy eigenstate of your hamiltonian and thus doesn't evolve at all.
So in particular, its norm being preserved is expected.
For other states i do see the norm drop:

```python
from tenpy.models.model import CouplingModel, MPOModel, NearestNeighborModel
from tenpy.models.lattice import Chain
from tenpy.networks.site import SpinHalfSite
from tenpy.networks.mps import MPS
from tenpy.algorithms.tebd import TEBDEngine
import numpy as np


class QCPModel(CouplingModel, MPOModel, NearestNeighborModel):
    """
    Implementation of part 1 in Section 2B
    """

    def __init__(self, params):
        L = params.get('L')
        omega = params.get('omega')
        gamma = params.get('gamma')
        bc_MPS = params.get('bc_MPS', 'finite')

        site = SpinHalfSite(conserve='None')  # no conserved quantities

        # Add operators to sites
        sigmax = np.array([[0, 1], [1, 0]])
        number_op = np.array([[0, 0], [0, 1]])
        annihilation_op = np.array([[0, 1], [0, 0]])
        site.add_op('sigmax', sigmax)
        site.add_op('number_op', number_op)
        site.add_op('annihilation_op', annihilation_op)

        oned_lattice = Chain(L=L, site=site, bc='open', bc_MPS=bc_MPS)

        CouplingModel.__init__(self, oned_lattice)
        for i in range(L - 1):
            self.add_coupling_term(strength=omega, i=i, j=i + 1, op_i='sigmax', op_j='number_op', plus_hc=False)
            self.add_coupling_term(strength=omega, i=i, j=i + 1, op_i='number_op', op_j='sigmax', plus_hc=False)

        for i in range(L):
            self.add_onsite_term(strength=-gamma * 1j / 2, i=i, op='number_op')

        # generate MPO for DMRG
        MPOModel.__init__(self, oned_lattice, self.calc_H_MPO())

        # generate H_bond for TEBD
        NearestNeighborModel.__init__(self, oned_lattice, self.calc_H_bond())


def main():
    L = 11
    model = QCPModel(dict(L=L, gamma=1, omega=6, bc_MPS='finite', explicit_plus_hc=False))
    options = dict(
        preserve_norm=False,
        N_steps=6,
        dt=.05,
        trunc_params=dict(
            chi_max=100,
            svd_min=1e-12
        )
    )

    initial_states = dict(
        psi_right = MPS.from_product_state(model.lat.mps_sites(), [np.array([1., 1.]) / np.sqrt(2)] * L, bc='finite'),
        psi_up = MPS.from_product_state(model.lat.mps_sites(), ["up"] * L, bc='finite'),
        psi_down = MPS.from_product_state(model.lat.mps_sites(), ["down"] * L, bc='finite')
    )

    for which, psi in initial_states.items():
        print()
        print(f'Evolving {which}')
        print(f'Norm before evolution: {psi.norm}')
        solver = TEBDEngine(psi, model, options)
        solver.run()
        print(f'Norm after evolution: {psi.norm}')


if __name__ == '__main__':
    main()
```

output:
```
Evolving psi_right
Norm before evolution: 1.0
Norm after evolution: 0.37018830009481135

Evolving psi_up
Norm before evolution: 1.0
Norm after evolution: 1.0

Evolving psi_down
Norm before evolution: 1.0
Norm after evolution: 0.33723867494842963
```

It seems that everything is in order and there are no bugs, so I will close this.
Feel free to reopen if I am missing something here
