### ISSUE TITLE
Review MANIFEST.in

### ISSUE THREAD

**Issue by Jakob-Unfried** [tenpy/tenpy#328]
The contents look outdated.
- `setup.cfg` and `pytest.ini` no longer exist
- `pyproject.toml` should probably make this list

Should also double check if the file is actually needed / used by the build system.
If it is used, I am confused that the non-existing files have not caused any problems yet since #237.

**Comment by jhauschild** [comment]
It should be used by setuptools to decide what's included in the pip package.
The reason why it didn't make issues yet is that we didn't have official releases since #237...
