### ISSUE TITLE
Incorrect reporting of truncation error in TDVP

### ISSUE THREAD

**Issue by aaronszaszG** [tenpy/tenpy#339]
Using TwoSiteTDVPEngine, the `update_local` method both updates `self.trunc_err` and appends the truncated weight from the current bond to `self.trunc_err_list`.  Then `sweep` returns the maximum of `self.trunc_err_list`, and in `evolve` this maximum gets added to `self.trunc_err`.  The result is that the error from the largest truncation is counted twice.

If the engine is called `tdvp_engine`, you can check that 
`1 - np.prod([1-2*x for x in (tdvp_engine.trunc_err_list + [max(tdvp_engine.trunc_err_list)]) ])`
returns the same value as
`tdvp_engine.trunc_err.ov_err`

So the largest truncation is counted twice

I have not checked whether this applies to other time evolution engines

**Comment by Jakob-Unfried** [comment]
Thanks for the report, see the PR linked above.
You are correct and the current implementation definitely overcounts the error.
I am reasonably sure that the other time evolution algorithms are unaffected.
Beware though, that error measures for MPS time evolution are a subtle business...
