### ISSUE TITLE
periodic conditions

### ISSUE THREAD

**Issue by Diyorazh** [tenpy/tenpy#34]
Hi there, 
I am trying to use your method to solve Hamiltonians with periodic conditions.
I saw that from your website you said you can add couplings by >>> self.add_coupling([1.5, 1.], 0, 'Sz', 0, 'Sz', dx)
May I ask what does "[1.5, 1.]" mean here?
thank you!
Diyora Zhang

![Screen Shot 2019-05-12 at 3 04 40 PM](https://user-images.githubusercontent.com/34129418/57578944-875f6280-74c7-11e9-97e0-287c75ae0b14.png)

**Comment by jhauschild** [comment]
Welcome!
Please post questions like this in our [community forum ](https://tenpy.johannes-hauschild.de).
Simply open a thread in the FAQ section. I'll be happy to answer it over there.
