### ISSUE TITLE
possible_couplings do not return suitable lat_indices in some cases

### ISSUE THREAD

**Issue by coolplay** [tenpy/tenpy#36]
I want to study infinite cylinder on square lattice with longer couplings, but lat.possible_couplings do not return suitable lattice indices to index coupling_shape in the following case.
```
from tenpy.models.lattice import Square
lat = Square(1, 4, None, bc='periodic')
l = lat.possible_couplings(0, 0, [-2,1])
print(l[-2]) # lattice indices
print(l[-1]) # coupling_shape
```

```
[[-2  0]
 [-2  1]
 [-2  2]
 [-2  3]]
(1, 4)
```

**Comment by jhauschild** [comment]
First of all, you need to explicitly specify `bc_MPS='infinite'`, otherwise the system is to be considered finite and have only the 1x4=4 sites.

The results look fine to me. What would you expect do get?

You can visualize it with the following code:
```python
from tenpy.models.lattice import Square
import matplotlib.pyplot as plt
lat = Square(1, 4, None, bc='periodic', bc_MPS='infinite')
print(lat.possible_couplings(0, 0, [-2,1]))
ax = plt.gca()
lat.plot_sites(ax)
lat.plot_coupling(ax, lat.nearest_neighbors, color='k')
lat.plot_coupling(ax, [(0, 0, [-2, 1])], color='g')  # your couplings
plt.show()
```

**Comment by coolplay** [comment]
Thanks for your quick reply!

I was actually trying to add NNNNN hopping to the Hamiltonian on infinite length cylinder with `add_coupling()`, which uses `lat_indices` to index coupling strength whose shape is specified by `coupling_shape` and surely gets an IndexError. How do I overcome this problem without modifying tenpy source code?

**Comment by jhauschild** [comment]
If you give as single floating point number as `strength` in tenpy.models.CouplingMPOModel.add_coupling, it will simply take the same value for each connection.
Or do you need different strengths for different next-next-next-nearest-neighbor couplings?

**Comment by coolplay** [comment]
Unfortunately, I'll probably study charge pumping which makes coupling strengths differ on boundaries.

**Comment by jhauschild** [comment]
There's a function to add the complex phases of an external flux. Try something like 
```python
for u1, u2, dx in self.lat.nearest_neighbors:
   t_phi = self.coupling_strength_add_ext_flux(t, dx, [0, phi_ext])
   self.add_coupling(t_phi, u1, 'Cd', u2, 'C', dx, 'JW', True, category='t Cd_i C_j')
   self.add_coupling(np.conj(t_phi), u2, 'Cd', u1, 'C', -dx, 'JW', True, category='t Cd_i C_j h.c.')  # h.c.
```

**Comment by coolplay** [comment]
I just changed coupling strength to a single number, but the IndexError still persisted. I think some fixes are needed in `lat.possible_couplings()` to address long range coupling for infinite cylinder. Thank you for clarification.

**Comment by jhauschild** [comment]
TeNPy is written to handle long range couplings for infinite cylinders, so this should definitely work.
Could you show me the traceback and (parts of) the code which generate the error message?

**Comment by coolplay** [comment]
I'll post the code later since it's middle night here. The IndexErrorr emits from [https://github.com/tenpy/tenpy/blob/10b2696da1447d37ddc53db82e9d1d226c188f8b/tenpy/models/model.py#L768](here).

**Comment by coolplay** [comment]
Minimal code to reproduce IndexError
```
from tenpy.networks.site import BosonSite
from tenpy.models.lattice import Square
from tenpy.models.bose_hubbard import BoseHubbardModel
from tenpy.tools.params import get_parameter

class BoseHubbardTest(BoseHubbardModel):
    def init_terms(self, model_params):
        t4 = get_parameter(model_params, 't', 1., self.name, True)
        u1, u2, dx = (0, 0, [-2,1]) # one of NNNNN for illustration
        self.add_coupling(t4, u1, 'Bd', u2, 'B', dx)
        self.add_coupling(t4, u2, 'Bd', u1, 'B', -dx)  # h.c.

square = Square(1, 4, BosonSite(), bc='periodic', bc_MPS='infinite')
model_params = dict(lattice = square)
model = BoseHubbardTest(model_params)
```

**Comment by jhauschild** [comment]
Thanks for pointing it out, it should now be fixed.
