### ISSUE TITLE
FermionicHubbardModel on-site terms

### ISSUE THREAD

**Issue by giladkishony** [tenpy/tenpy#42]
The problem is in the addition of the on-site terms:

for u in range(len(self.lat.unit_cell)):
    self.add_onsite(mu, 0, 'Ntot')
    self.add_onsite(U, 0, 'NuNd')

Should be:

for u in range(len(self.lat.unit_cell)):
    self.add_onsite(mu, u, 'Ntot')
    self.add_onsite(U, u, 'NuNd')

Note that this does not affect the case of lattice='chain' so it might have been overlooked.

**Comment by jhauschild** [comment]
Thanks for pointing it out!
