### ISSUE TITLE
Re-Licensing under Apache v2

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#462]
Up until now, TeNPy is licensed under the [GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html) license.
It is one of the major open source licenses, e.g. the Linux kernel is released with it, and it is the reason why all linux distros are open source. However, the license is quite strict in enforcing what's called "copyleft": anybody who want's to modify and extend the code has to publish his code as open source under the very same GPL license. This is a red flag for companies like IBM developing quiskit or quantum computing start-ups and hinders IBM to use TeNPy as a backend for qiskit.

@bartandrews hence suggested re-license TeNPy under the [Apache v2](http://www.apache.org/licenses/LICENSE-2.0) license instead. Although I was the one originally choosing the GPLv3 license, I fully support the change to Apache v2. I put many hours into TeNpy in the hope that it will be useful for the scientific community, and blocking the further development of it due to licensing issues seems counter-productive.
Apache v2 is also a popular license with many other scientific python projects, including [quiskit](https://github.com/Qiskit/qiskit/blob/main/LICENSE.txt),  [tensorflow](https://github.com/tensorflow/tensorflow/blob/master/LICENSE) and the [cytnx](https://github.com/Cytnx-dev/Cytnx/blob/master/LICENSE) library that we're planning to collaborate with.

To compare the licenses, you might want to read the full texts linked above or check out the bullet point summaries on
choosealicense.com, [Apache v2](https://choosealicense.com/licenses/apache-2.0/) vs [GPL v3](https://choosealicense.com/licenses/gpl-3.0/). By changing to Apache v2, we're essentially dropping the copyleft, i.e. become more permissive towards future developers to choose their own license for their contributions. In theory, someone could even do that closed source (which the copyleft of GPL would avoid), but I think the risk for that is just a very negligible epsilon > 0.

With this issue, I'm hence asking the contributors of TeNPy for their consent or possible objections to this re-licensing. 
For the legal documentation, it would be great if everyone of the current contributors (in particular the authors of our [TeNPy v1 paper](https://arxiv.org/abs/2408.02010)) could give a short comment like "changing the license is fine with me" - or raise objections and concerns, should there be any. Thank you!

**Comment by bartandrews** [comment]
changing the license is fine with me

**Comment by Jakob-Unfried** [comment]
changing the license is fine with me

**Comment by Lschoon** [comment]
Changing the license is fine by me. Thanks!

**Comment by jhauschild** [comment]
Wilhem Kadow answered by Mail: 

> Thanks so much for taking care of this. Changing the license is fine with me.

**Comment by nikirchner** [comment]
Changing the license is fine with me.

**Comment by sajantanand** [comment]
Changing the license is fine with me.

**Comment by Jack-Kemp** [comment]
Changing the license is fine with me. Thank you for organising this.

**Comment by MartinHefel** [comment]
Changing the license is fine with me.

**Comment by yantaow** [comment]
changing the license is fine with me. Thanks!

**Comment by anton-romen** [comment]
Changing the license is fine with me. Thanks!

**Comment by jangeiger** [comment]
Changing the license is fine with me. Thanks!

**Comment by tomohiro-soejima** [comment]
I support changing the license!

**Comment by p-thoma** [comment]
Changing the license is fine with me, thank you!

**Comment by mrader1248** [comment]
Changing the license is fine with me. Thank you for taking care of this!

**Comment by jhauschild** [comment]
I also got  confirmations from Dan Parker, Maximilian Schulz and Samuel Scalet,  Philipp Zechmann and Markus Drescher.

With that, the vast majority of team (making up nearly all explicit code contributions) has explicitly explicitly confirmed, while no one has raised any concerns with the license change.
Given that throughout the repository the copyright is dedicated to the whole "TeNPy developer team" rather than individuals, I think we can proceed and say that we as a whole team agreed to change the license. Hence, I'll proceed to update the license.
