### ISSUE TITLE
Model enhancements

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#54]
- [x] add `phi_ext` parameter to further models, e.g. `fermions_spinless`.
- [x] implement Haldane model from the example #37 as a new model
- [x] use explicit `categories` for the different coupling terms in the models
- [x] Could obtain `SpinChainNNN` from `SpinChainNNN2` by grouping sites. How to make it a `NearestNeighborModel`?
- [x] Provide documentation on grouping sites.

**Comment by jhauschild** [comment]
I've added the function `tenpy.model.NearestNeighborModel.from_MPOModel`, which can be used to get a `NearestNeighborModel` from `SpinChainNNN2`. It is not a `NearestNeighborModel` itself, though.

**Comment by jhauschild** [comment]
For the last point see #55

**Comment by Jakob-Unfried** [comment]
First point: #273, 2 and 3 are done. 5 has its own issue #55.

Point 4 is the only thing left, but I think the current solution is good.
Do you want to do anything else there? @jhauschild ?

**Comment by jhauschild** [comment]
Point 4 is also solved in the Simulation.group_sites_for_algorithm through the `group_to_NearestNeighborModel` option.
I'll hence close this
