### ISSUE TITLE
Group and split documentation

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#55]
Provide examples how to group and split sites. Test that everything works as expected.

**Comment by Jakob-Unfried** [comment]
Test coverage looks good to me, e.g. [`test_mps.test_group()`](https://github.com/tenpy/tenpy/blob/4ec260ed6160c4e4d6505f24fee679932a5ec3ce/tests/test_mps.py#L391) and [`test_mps.test_fixes_issue_197()`](https://github.com/tenpy/tenpy/blob/4ec260ed6160c4e4d6505f24fee679932a5ec3ce/tests/test_mps.py#L421).

On the example side we have grouping in [`c_tebd.py`](https://github.com/tenpy/tenpy/blob/4ec260ed6160c4e4d6505f24fee679932a5ec3ce/examples/c_tebd.py#L157).
Do you want more examples @jhauschild ?
