### ISSUE TITLE
add_hc flag for MPO

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#58]
For models with e.g. Heisenberg couplings or fermionic/bosonic hoppings, explicitly adding the hermitian conjugate increases the bond dimension of the MPO. This increases the memory requirements of the `MPOEnvironment` during DMRG.

Instead of adding these terms explicitly to the MPO, we can set a flag to the MPO that the hermitian conjugate needs to be added later, and explicitly add the hermitian conjugate in the `matvec` operations of the effective OneSite/TwoSite Hamiltonians.

Steps: 
- [x] Add a flag to the CouplingModel that h.c. terms need to be added later.
- [x] Use this flag in the generation of bond terms of the NearestNeighbor model.
- [x] Add flag to MPO
- [x] Adjust generation of effective Hamiltonians to use alternative `matvec` depending on the flag.

**Comment by Lschoon** [comment]
As an intermediate step:

- [ ] Add the flag to `add_coupling()` to create a h.c. term of the current coupling.
- [ ] Test this in at least one model.

**Comment by Lschoon** [comment]
Question for @jhauschild: all documentation suggests that the hermitian conjugate of `add_coupling(t, u1, 'Cd', u2, 'C', dx)` is `add_coupling(np.conj(t), u2, 'C', u1, 'Cd', -dx)`. However, this is not followed in many model codes. Consider the following cases:

From `XXZChain`:
```
self.add_coupling(Jxx * 0.5, 0, 'Sp', 0, 'Sm', 1)
self.add_coupling(np.conj(Jxx * 0.5), 0, 'Sp', 0, 'Sm', -1)  # h.c.
```
Here, `u1 = u2 = 0`. The code as it is written here seems right; it creates a term `J S^+_i S^-_{i+1}` on the first line, then a term `J S^+_{i+1} S^-_i` on the second line. However, strictly following the documentation, the second line should be `self.add_coupling(np.conj(Jxx * 0.5), 0, 'Sm', 0, 'Sp', -1)`, which seems to give us a term `J S^-_{i+1} S^+_i`, i.e., the same term as the first line.

From `FermionModel` (similar example but with `u1 != u2`:
```
self.add_coupling(-J, u1, 'Cd', u2, 'C', dx)
self.add_coupling(np.conj(-J),` u2, 'Cd', u1, 'C', -dx)  # h.c.
```

From `SpinModel` (lines 1-2 disagree with documentation, lines 3-4 agree):
```
self.add_coupling((Jx + Jy) / 4., u1, 'Sp', u2, 'Sm', dx)
self.add_coupling(np.conj((Jx + Jy) / 4.), u2, 'Sp', u1, 'Sm', -dx)  # h.c.
self.add_coupling((Jx - Jy) / 4., u1, 'Sp', u2, 'Sp', dx)
self.add_coupling(np.conj((Jx - Jy) / 4.), u2, 'Sm', u1, 'Sm', -dx)  # h.c.
```

This suggests that either the documentation oversimplifies Hermitian conjugation, or the majority of model codes is wrong, or I am missing something obvious. Any input?

**Comment by jhauschild** [comment]
>  all documentation suggests that the hermitian conjugate of `add_coupling(t, u1, 'Cd', u2, 'C', dx)` is `add_coupling(np.conj(t), u2, 'C', u1, 'Cd', -dx)`
Really? That's wrong, I think..... Where did you find this?
The correct way to add the h.c. for `add_coupling(t, u1, 'A', u2, 'B', dx)` is `add_coupling(np.conj(t), u2, 'hc(B)', u1, 'hc(A)', -dx)`

As far as I see, this is what's documented in [add_coupling](https://tenpy.readthedocs.io/en/latest/reference/tenpy.models.model.CouplingModel.html#tenpy.models.model.CouplingModel.add_coupling), even though it might be a bit hard to read.

This is indeed what's done in the models, isn't it; I'm pretty sure the models are fine.
In the tests of the models, I usually check for hermiticity with `M.H_MPO.is_hermitian()`, which passes....
I guess, we should also move this test into `Model.test_sanity()` somehow.

Btw, for the MultiCouplingModel, things are a bit more complicated. We need to redefine the arguments of `add_multi_coupling` to not handle the first operator in a special way. I will take care of that.

**Comment by Lschoon** [comment]
Oops! I see that I misread the documentation to state `add_coupling(np.conj(t), u2, 'hc(A)', u1, 'hc(B)', -dx)` as conjugate. This makes sense now.

I am thinking about sanity checks, these might depend on the precise implementation of the h.c. automation.

**Comment by Lschoon** [comment]
Quick update (note that development is taking place in my [dev branch](https://github.com/Lschoon/tenpy/tree/dev)):

The `add_hc` flag in `add_coupling()` seems to work as expected in most cases. To this end, every `Site` subclass defines a dictionary to look up the conjugates to each operator. This requires minimal changes to the code, but leads to the following problem.

A model that does not use a prebuilt site class, but rather a basic `Site` with custom operators (e.g., `XXZChain`, which notably is not a subclass of `CouplingMPOModel`) has no way of knowing what the Hermitian conjugates are. Changing things such that conjugates can be defined in this way of model creation would clutter the interface to `Site`. Can we adopt the policy that automatic Hermitian conjugates will only work with predefined Site classes?

Additionally, I would like to include a sanity check in the `Site` class to check whether each operater has an associated conjugate. This will be easiest if by the time `Site.__init__()` gets called, all operators and conjugates are known. @jhauschild, is there a reason `SpinHalfSite.__init__()` adds operators after calling `Site.__init__()`?

**Comment by jhauschild** [comment]
I allow users to add operators later on, *after* the site has been constructed, simply because that way you don't need to define a new site class just because you add an operator. For example, if somebody groups two sites together, he can add operators which were previously two-site operators later on.
For that reason, I think we should not *enforce* that we know the hermitian conjugate of all operators. However, since operators are added with Site.add_op(...), we can actually adjust just that function to check wheter the h.c. operator was defined already and include it in the list of hermitian operators.
I implemented this and just made a pull request to your dev branch with it.
I also implemented a function to get the h.c. operators, to ensure more sensible error messages, and to ensure that it still works for products of operators, e.g. "Bd Bd" is a valid operator name, but not a defined onsite operator name.


PS: Determining the h.c. operator automatically is also less prone to errors, I think. In fact, in your manually defined list of h.c. operators for the Boson Site, you still had a typo....
To avoid that, we should also add a small test in Site.test_sanity(), which just checks that `self.hc_ops` only contains operators which are indeed the h.c. of each other.

**Comment by jhauschild** [comment]
@Lschoon did you work any further on this?
If not, I'd suggest that I don't distract you from writing your thesis and quickly implement it myself.

I added the `add_hc` flag for `MultiCouplingModel.add_multi_coupling` and some tests today, pushed to my `dev` branch.

**Comment by Lschoon** [comment]
Apologies, things have been a little crazy around here. I have now settled into a remote working regimen and will be able to work on this. I did implement the suggestions I commented (but had not pushed them to GitHub yet). I have just pulled your `dev` branch into mine and am laying out the further changes needed to automate hcs ad model level. I will be working to actually implement those over the course of next week (have some other commitments today).

If you would like to take over, go ahead. Otherwise, please let me know if you have any comments.

**Comment by Lschoon** [comment]
Let me also flag up a small bug: https://github.com/Lschoon/tenpy/pull/10/commits/64d645bb254c82a3ab7e9c17e316a405e58a8b04 has broken `io_test`'s ability to check if data from older versions is loaded correctly. As a workaround, I now (per https://github.com/Lschoon/tenpy/commit/451d2c54278393883a7c4f9ce8e80cf67f14d87f) check whether the `Site` has an attribute `hc_ops` before checking if the conjugates are correct.

This works, but I am a bit worried it reduces the efficacy of the sanity check too much. Any thoughts?

**Comment by jhauschild** [comment]
I just wanted to offer my help; if you have some time to continue working on this, I won't stop you ;-)
I'm just asking because I want to wrap things up for the next release.
With the new way of using `add_hc` and changed arguments for `add_multi_coupling`, it contains a big backwards-incompatible change, which I'd like to include into the next release.
I also wanted to implement a few other backwards incompatbile changes by then, so I'll focus on that then.

You really don't need to worry about the efficiency of that (or any other) sanity check. 
Sanity checks shouldn't be performance critical - otherwise we shouldn't do any sanity check at all.
I think the workaround with `hasattr` in `test_sanity` is fine.
The perfect way would be to check for that missing attribute during loading from file for both HDF5 and pickle, but that's not completely trivial to implement (in particular for loading with pickle). I don't think it's worth going through it right now and for that change.

**Comment by Lschoon** [comment]
Question: You suggested adjusting `EffectiveH.matvec` to depend on the h.c. flag. It seems that this is unnecessary if we adjust `MPOEnvironment.get_W()` (and potentially `get_LP()` and `get_RP()`). That would keep the flag a model/MPO property.

(Also, note that I was not worried about the _efficiency_ of the sanity check, but rather about whether the sanity check would still work in the general case. I have now convinced myself that it does.)

**Comment by Lschoon** [comment]
To keep track of what is going on (essentially a note to self), here is the intended behaviour of the h.c. flags. This can still change if I have misunderstood things, or we decide to do things slightly differently.
- If, during model generation, `add_coupling()` is called with `add_hc=True`, the conjugate of the coupling is added to the MPO, no questions asked. The MPO bond dimension is not reduced. For this, the `add_hc` flag just needs to be handled in `add_coupling()` and `add_multi_coupling()`.
- If a model is generated with a parameter `'add_hcs':True` (note the extra `s`), _all_ terms will be considered to have a conjugate. These are not added to the MPO, but rather computed at runtime. This means that h.c.-invariant terms should be defined with a prefactor that is 1/2 of what is in the analytical Hamiltonian.

Classes that need to handle `add_hcs` (I fear this list is incomplete):
- `CouplingMPOModel`
- `CouplingModel`
- `MPO`

@jhauschild, feel free to comment and disagree with any of this.

**Comment by jhauschild** [comment]
First of all, since `add_hc` and `add_hcs` are very similar and can easily be confused, I'd suggest to use something like `explicit_add_hc` instead of `add_hcs`. I'll use that in the following, feel free to suggest another name as well.

I'm not sure whether you got the full idea of the `explicit_add_hc` flag. Let me clarify what I had in mind:

* We need the flag `explicit_add_hc` for the `MPO` and  the `CouplingModel`.
	For the `CouplingModel`, the idea of the flag is that the represented Hamiltonian is `terms + hc(terms)` where `terms` are the terms represented in `self.coupling_terms` and `self.onsite_terms`.
	Similarly, for the `MPO`, the flag indicates that the Operator we actually represent is `self + hc(self)`.
* The `add_hc` argument in `add_coupling` indicates that the particular coupling is not hermitian and needs the h.c. terms as well.
  If the `explicit_add_hc` flag of the model is False, it will just call `self.add_coupling(...)` again with appropriate hermition-conjugated operators in switched order to add the h.c. term, as it does right now.

  If, however, `explicit_add_hc` is True, `add_coupling` will *not* call `self.add_coupling(...)` again even for `add_hc=True`.
  Moreover, if `add_hc=False`, it will *divide the strength by 2*.
  Hence, if `explicit_add_hc`, `add_coupling` only adds half of the terms to `self.coupling_terms` - but `self` represents the same terms as if `explicit_add_hc=False`.
* Same holds for `MultiCouplingModel.add_multi_coupling`.
* Similarly, we also need to divide the strenght of the onsite terms by 2 if `explicit_add_hc=True`, i.e. adjust `CouplingModel.add_onsite`
* Then we adjust `CouplingModel.calc_H_onsite`, and `calc_H_bond` to explicitly add the hermitian conjugate terms, such that `H_bond` results in the same as before, independent of `explicit_add_hc`, or `0.5*(H_bond +hc(H_bond)` to be precise. This will make sure algorithms like TEBD still works the same way, whether you use `explicit_add_hc` or not.
* Moreover, we adjust `CouplingModel.calc_H_MPO` to set the flag `explicit_add_hc` of the MPO to True. Note that we end up with smaller bond dimension of the MPO if the `add_hc` flag of `add_coupling` was used during the definiton of the Model.
* All algorithms using an MPO should check for the `explicit_add_hc` flag of the MPO to know whether they need to explicitly add the h.c. of the MPO.
  As of know, that's just DMRG and TDVP.
  - For DMRG, the only thing we need to do is to change what the `EffectiveH.matvec` does. We can do that somewhere inside the `EffectiveH.__init__()` with a "Monkey-Patch", similarly as we do right now for the case of non-empty `ortho_to_envs`. Monkey-patching makes the code a bit hard to read, so we should at least explicitly state that in comments/doc-strings.
  - For TDVP: we should rewrite it to use the very same EffectiveH class...
  But that's not gonna happen soon, so for now we should just 
  ```python
  if H.explicit_add_hc:
     raise NotImplementedError("TDVP does not respect 'MPO.explicit_add_hc' flag")`
  ```

The `CouplingMPOModel` only needs to handle `explicit_add_hc` in the sense that it reads out the parameter from the dict and passes it on to the `CouplingModel.__init__()`.


Also, we should document all that somewhere. I just don't know, where....

**Comment by Lschoon** [comment]
Thank you so much for this! I had understood the essential funcionality, but did not have a good overview of where changes needed to be implemented.

I propose `add_hc_to_MPO` as a flag, since both flags seem more or less explicit to me. 

I also suggest we document this in the [documentation for models](https://tenpy.readthedocs.io/en/latest/intro/model.html). Perhaps we will need to split that part of the documentation, as it is getting rather long.

**Comment by Lschoon** [comment]
> Then we adjust CouplingModel.calc_H_onsite, and calc_H_bond to explicitly add the hermitian conjugate terms, such that H_bond results in the same as before, independent of explicit_add_hc, or 0.5*(H_bond +hc(H_bond) to be precise. This will make sure algorithms like TEBD still works the same way, whether you use explicit_add_hc or not.

This probably necessitates removing the deprecation warning from `calc_H_onsite`. As I have little to no experience in working with `tenpy.terms`, please check if the edits in https://github.com/Lschoon/tenpy/commit/986c93f0a82a676756d8746da4d02627c0c043b2 are correct and sufficient to make `calc_H_onsite` and `calc_H_bond` work.

**Comment by Lschoon** [comment]
Alright, final update of today (will continue work on this tomorrow). 

I decided to implement the Hermitian conjugation in the generation of the `EffectiveH`s, rather than in their `matvec`. This seemed like an easier and slightly more intuitive place to do so.

I have created a test file to check whether the h.c. automation works, based on the TFI test file. Tests pass for `'finite'`, but fail for `'infinite'` MPS. I hope to track down the problem tomorrow, any input is of course welcome.

**Comment by jhauschild** [comment]
> I propose `add_hc_to_MPO` as a flag, since both flags seem more or less explicit to me.

 Sounds good to me

 > I also suggest we document this in the documentation for models. Perhaps we will need to split that part of the documentation, as it is getting rather long.

Yes, that's probably the best place to document it. Probably as a separate section at the end of it.

> This probably necessitates removing the deprecation warning from calc_H_onsite. As I have little to no experience in working with tenpy.terms, please check if the edits in Lschoon@986c93f are correct and sufficient to make calc_H_onsite and calc_H_bond work.

Sorry, I wasn't aware any more that I deprecated this :D
In fact, good that I did - the only point where `calc_H_onsite` would have been called is in `calc_H_bond`; the MPO needs to handle adding the `h.c.` terms differently. For that reason, I think it's actually better to keep `calc_H_onsite` deprecated and keep the code dealing with adding the `h.c.` terms in `calc_H_bond` terms explicitly. In you change, you add the `h.c.` to the `H_bond` terms at the end of `calc_H_bond` - this is the perfect place, but it means that we *shouldn't* add the `h.c.` terms to the onsite terms before hand.
For your fix:  some entries of `H_bond` can be `None`, in particular if `bc="finite"` the first term should be `None`, and this needs to be handled. Also, when adding the `h.c.` term of the array, we should transpose to ensure the same order of legs. Suggested code:
```python
# ... in calc_H_bond()
if finite:
    assert H_bond[0] is None
if self.add_hc_to_MPO:
    # self representes the terms of `ct` and `ot` + their hermitian conjugates
    # so we need to explicitly add the hermitian conjugate terms
    for i, Hb in enumerate(H_bond):
        if Hb is not None:
            H_bond[i] = Hb + Hb.conj().itranspose(Hb.get_leg_labels())
return H_bond
```

**Comment by jhauschild** [comment]
> I decided to implement the Hermitian conjugation in the generation of the `EffectiveH`s, rather than in their `matvec`. This seemed like an easier and slightly more intuitive place to do so.

Unfortunately, this doesn't work. (Your tests didn't actually use the `add_hc_to_MPO` flag at all because of a typo.)
The problem is that the `conj` leads to conjugated virtual legs of the MPO, such that e.g. `LP` and `LP.conj()` cannot be added to each other. The way to go here is really to do the `matvec` twice per external `EffectiveH.matvec()` call, once for `self` and once for `hc(self)`.

**Comment by jhauschild** [comment]
I'm looking into this right know. A small to-do list to keep track:
- [x] ExactDiag.build_full_H_from_mpo() should also respect the flag
- [ ] fix `EffectiveH.matvec()`
- [ ] fix `MPO.from_hdf5()` and `MPO.save_hdf5()` to save/load the flag as well.
- [ ] document `add_hc_to_MPO` in Model userguide
- [ ] document `add_hc` flag of `add_coupling` in Model userguide
- [ ] use `add_hc` flag for models implemented in TeNPy
- [ ] tests

**Comment by jhauschild** [comment]
Okay, I've fixed most of it, see 424a3cb7df8d2da0a3f2532cc1bb8e654a304024 and previous commits in my dev branch. I hope you don't mind that I took over the implementation of adding the h.c. for the matvec, I felt like it was easier if I just do it than if I try to explain it to you.
I tried to make the code cleaner now, by not using monkey-patches any more and instead defining explicit wrapper classes.
@Lschoon Can you confirm that the `EffectiveHPlusHC` is readable? And does `Sweep.make_eff_H` make sense to you?

I think when we updated the documentation we're ready to merge it in the master branch. Do you agree?

**Comment by Lschoon** [comment]
I absolutely don't mind. I admit to a massive facepalm when I realised my mistake in `matvec`...

`EffectiveHPlusHC` and `Sweep.make_eff_H` make perfect sense to me.

I had already included the `add_hc` flag in `FermionModel`, `XXZChain` and `SpinModel`. Can add the flag to other models too, if necessary.

I will work on the documentation today. Am I correct that the changelog does not mention the flags as of now?

**Comment by Lschoon** [comment]
I have written some documentation and created a pull request: https://github.com/tenpy/tenpy/pull/104. You should be able to review and edit there.

**Comment by jhauschild** [comment]
@lschoon, thank you so much for this!

I'll quickly rewrite the other models to use the `add_hc` flag as well, just for consistency, and if people look into them for examples on how to define their own models.

Some final questions before we should close this:
- I just thought about renaming the `add_hc` argument of `add_coupling` to `plus_hc`; do you think this would this be more intuitive?
- It's quite trivial to add the `add_hc` argument to `add_onsite` as well, shouldn't we do that as well?

**Comment by jhauschild** [comment]
Last question: yes, we should.... For example, for the SpinChainNNN

**Comment by Lschoon** [comment]
I don't see a difference in intuitive-ness between `add_hc` and `plus_hc`. Of course, if we later find this somehow causes confusion in users, a refactor is easy to implement.

**Comment by jhauschild** [comment]
Right now, no one is using it yet, but later on we break backwards compatibility. So if we rename it, we should do it now.

I actually think `plus_hc` or maybe even better `plus_h_c` might be more intuitive, because I (personally) directly connect the phrase "plus h.c." with writing down `H = sum (... + h.c)` whereas in `add_hc` I connect the `add` to the `add_*` from `add_onsite` or `add_coupling` and then need realize that that `hc` refers to `hermitian conjugate`. Isn't it the same for you?
I'm not sure if we should we rename the `add_hc_to_MPO` flag as well for consistency?

Do you have any objections against renaming it right now?

**Comment by Lschoon** [comment]
I have no objections to either name, if you prefer `plus` to `add`, be my guest! Perhaps, having worked on this a while, I struggle seeing how one could not understand what these names mean. I _am_ having trouble coming up with an alternative name for `add_hc_to_MPO` that is consistent with `plus` (`plus_hc_in_MPO`, maybe, although that does not sound quite right...), so maybe that would be a counter-argument?

**Comment by jhauschild** [comment]
I renamed `add_hc -> plus_hc` and `add_hc_to_MPO -> explicit_plus_hc`.
I think the latter is clearer since it also affects the onsite and coupling terms of the `CouplingModel`, and not only the MPO. 
Further, I added the `plus_hc` argument to `CouplingModel.add_*_term` methods and made them respect the `explicit_plus_hc` as well.

Finally done!
