### ISSUE TITLE
Time evolution method W_I, W_II

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#62]
When #60 is implemented, it shouldn't be that hard any more to also implement the 
W_I / W_II method from https://arxiv.org/abs/1407.1832

**Comment by halbleben** [comment]
This would be extremely useful as it's the currently most used method in state of the art 2D dynamics applications...

**Comment by jhauschild** [comment]
we're working on this, see #91

**Comment by jhauschild** [comment]
Done :)
