### ISSUE TITLE
[feature request] Kagome

### ISSUE THREAD

**Issue by mrader1248** [tenpy/tenpy#7]
First of all: I think you did a really great job by creating `tenpy`!

I was wondering, how one could use `tenpy` to simulate Kagome cylinders. For this reason I have implemented a class `Kagome`, which you can find below. If I understood the internals of `tenpy` correctly, this always corresponds to what is called YCn-0 in [PRX 7, 031020 (2017)](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.7.031020)? How could one implement YCn-2, YCn-4, ...? Wouldn't it be nice to have this built into `tenpy`? Thank you already in advance for your answers.

```
from tenpy.models.lattice import Lattice
import numpy as np

class Kagome(Lattice):
    
    def __init__(self, Lx, Ly, siteA, siteB, siteC, order="default", bc_MPS="finite"):

        basis = np.array([
            [2., 0.],
            [1., 3.**0.5]
        ])
        pos = (
            np.array([0., 0.]),
            np.array([0.5, -3.**0.5 / 2.]),
            np.array([1., 0.])
        )
        
        self.nearest_neighbors = [
            (0, 1, np.array([0, 0])),
            (0, 2, np.array([0, 0])),
            (1, 2, np.array([0, 0])),
            (1, 0, np.array([1, -1])),
            (2, 0, np.array([1, 0])),
            (2, 1, np.array([0, 1]))
        ]
        
        self.next_nearest_neighbors = [
            (0, 1, np.array([0, 1])), 
            (0, 2, np.array([-1, 1])),
            (1, 0, np.array([1, 0])),
            (1, 2, np.array([-1, 0])),
            (2, 0, np.array([0, 1])),
            (2, 1, np.array([-1, 1]))
        ]
        
        self.next_next_nearest_neighbors = [
            (0, 0, np.array([0, 1])),
            (1, 1, np.array([1, 0])),
            (2, 2, np.array([1, -1]))
        ]
        
        Lattice.__init__(self, [Lx, Ly], [siteA, siteB, siteC], order, bc_MPS, basis, pos)
```

**Comment by jhauschild** [comment]
First of all: this looks great! Would you mind to directly include this class in tenpy? If you create a pull request, you'll get the credit for it ;-) You can insert it below the Honeycomb class in `tenpy.models.lattice`.

Strictly speaking, the `Lattice` class does not now about the coupling boundary conditions. The `Lattice` defines the arrangement of sites, while the "Model" contains the couplings between the sites.
For this reason, it's actually the `CouplingModel`, where you specify the boundary conditions of the couplings.
Indeed, the couplings which you get from using the CouplingModel are what is called the YCn-0 in the referenced paper. Shifts of the form YCn-m are not implemented as of now, but I agree that this would be very useful. The place where the shifts would appear is in `CouplingModel.add_coupling` (and `MultiCouplingModel.add_multi_coupling`). Actually it shouldn't be too complicated to implement it...

PS: I guess you haven't seen it yet, but I've recently set up a [community forum](https://tenpy.johannes-hauschild.de/) with a subforum for feature requests ;-)

**Comment by jhauschild** [comment]
I've actually implemented this feature yesterday afternoon.
Commit 873319d39c7b1023bd1e0457e7d7a1cd22403647 adds the option of integers for `bc_coupling` in the `CouplingModel`. As it allows only a shift in the cylinder direction, it's not the most general case one can imagine, but I'm sure it suffices in practice - the more general case would only be needed in 3 or more dimensions...
Therefore, I close this "issue". If it's unclear how to use it, please ask in the forum :)
