### ISSUE TITLE
Consistent Parameter names

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#74]
Name the parameters of DMRG/TDVP/TEBD/... consistently.
Maybe just the `params` attribute for the corresponding engine?

Implementing this should probably wait until #49 is done.

**Comment by Lschoon** [comment]
Should potentially also wait for #39

**Comment by jhauschild** [comment]
It's probably necesary to think about how one can keep backwards compatibility when renaming the parameters. Maybe with python `@property` issuing a warning?

**Comment by jhauschild** [comment]
I think I closed this acidentally, this is still an issue...

**Comment by jhauschild** [comment]
implemented in 85655a91f27ae8eaffed17539a42edb14e86bdf5
