### ISSUE TITLE
Irregular lattices

### ISSUE THREAD

**Issue by jhauschild** [tenpy/tenpy#77]
The `IrregularLattice` needs to be implemented.
The idea would be to handle the case where one or multiple sites in a lattice are missing or where we have one or more additional sites.

The basic steps for the implementation are outlined at https://tenpy.johannes-hauschild.de/viewtopic.php?f=7&t=66.

**Comment by giladkishony** [comment]
What is currently the best way to substitute a different type of Sites in some arbitrary locations inside a regular lattice with some uniform type of Site?

**Comment by jhauschild** [comment]
In case someone is looking for this feature: https://tenpy.readthedocs.io/en/latest/intro/lattices.html#irregular-lattices
