### ISSUE TITLE
TwoSiteDMRGEngine has no attribute 'DMRG_params'

### ISSUE THREAD

**Issue by ge72tal** [tenpy/tenpy#88]
It seems that it is not possible any more to specify DMRG parameters with `eng.DMRG_params[]`. For instance, the example code `central_charge_ising` gives an error because of the line   `eng.DMRG_params['mixer'] = None`. It works fine if this line is commented out.

**Comment by jhauschild** [comment]
In the rewriting process of DMRG, #85, the parameters have been renamed to `self.engine_params`.
I quickly fixed the problem in 996c10d3d0c1d2c741905a2f433fe672f7887694.
However, this is only a temporary fix, I think we should rename the parameters of all the algorithm engines. See #74 .
