### ISSUE TITLE
Behaviour of Array addition with labels

### ISSUE THREAD

**Issue by Jakob-Unfried** [tenpy/tenpy#94]
When adding two arrays with a set of labelled legs that is (up to permutation) identical, the result of array addition can be counter-intuitive since it uses the order of legs instead of their labels to identify them.

I think performing such an addition should at least throw a warning, or even behave differently (reorder the legs of `other` in the addition, to match the order of `self`)

Toy code:
```
import numpy as np
import tenpy.linalg.np_conserved as npc

a1 = np.random.random([3, 3, 4])
a2 = np.swapaxes(a1, 0, 1)

t1 = npc.Array.from_ndarray_trivial(a1)
t1.iset_leg_labels(['a', 'b', 'c'])

t2 = npc.Array.from_ndarray_trivial(a2)
t2.iset_leg_labels(['b', 'a', 'c'])

print(npc.norm(t1 - t2))
```

**Comment by jhauschild** [comment]
Right, although it is counter-intuitive, it's the expected behaviour if you check the code - addition is based on the function `Array.iadd_prefactor_other` and this in turn on `Array.ibinary_blockwise`.

Unfortunately, changing this is backwards incompatible, so we should issue a warning for the next release if the leg labels are differently ordered, and than change the behaviour for the following release.

**Comment by jhauschild** [comment]
the above referenced commit fixes this problem by raising a warning for now, and already implements the necessary changes to actually do the transposition. 
In the doc-strings, I already mentioned the transpostion, but the code for now just gives a Future warning. After the next release, we change the behaviour, hence we should leave this issue open for the moment.

- [x] Implement changes
- [ ] after next release change behaviour

**Comment by jhauschild** [comment]
As a side comment, the same problem could occur with npc.inner.
However, it's well documented in this case. Do you think we should also throw a warning and change the behavior in that case?

**Comment by Jakob-Unfried** [comment]
I don't think `npc.inner` needs to do this.
When adding two tensors, i find it natural to have the same set of labels on the summands, but for the full contraction of two different tensors i would not. 
Especially since there is the `axes` argument, i don't expect anyone to run into unexpected behaviour here. It might be good to document the default behaviour `axes=None` though.

**Comment by jhauschild** [comment]
I thinks it's a good idea to ask people to specify axes explicitly, at least, whenever they `npc.inner`. Hence, the current default `None` gives a warning that the behaviour might change, and is currently equivalent to ``'range'``. There are places in tenpy, though, where I've now put a 'labels', so implementing this feature was helpful anyways.
